symfony/demo

- composer.json
- composer.lock
> Added ircmaxell/password-compat as a dependency

- src/AppBundle/Twig/SourceCodeExtension.php
> Added a method to unindent the source code of the controller

- app/Resources/assets/scss/main.scss
- web/css/app.css
> Fixed the styles of the form fields when the form contains errors

- app/Resources/translations/messages.ro.xliff
Romanian translations of initial i18n
> Translate to Romanian

- composer.lock
After discussing about the update policy in #76, it's been decided to keep the Symfony Demo application in sync with Symfony's stable versions. This PR updates the application to 2.7.1 version.
> Updated the application to Symfony 2.7.1

- app/Resources/translations/messages.pt_BR.xliff
- app/Resources/translations/validators.pt_BR.xliff
Hi!
Here is a complete Brazilian Portuguese translation
> Added Brazilian Portuguese translations

- app/Resources/translations/messages.de.xliff
ping @OskarStark What do you think?
> sync German translation

- app/Resources/translations/messages.de.xliff
This is a small mistranslation. (FÜr to Für)
> Mistranslation en to de

- app/check.php
We renamed `web/config.php` to `web/check.php` in https://github.com/symfony/symfony-demo/pull/74
> Fix web check filename

- app/Resources/translations/validators.ru.xliff
- app/Resources/translations/validators.uk.xliff
According to https://github.com/symfony/symfony-demo/commit/2c9a153e2da8378e438bb42510ebc552f5e743a9
> Add missing uk/ru translations

- web/check.php
Requirements checker: fix not matching closing tag
> Requirements checker: fix not matching closing tag

- src/AppBundle/Controller/SecurityController.php
> Removed not used namespace

- app/AppKernel.php
Move DoctrineFixturesBundle registration needs for developing only to the environment bundles section
> Register DoctrineFixturesBundle in the env bundles

- composer.json
- composer.lock
- src/AppBundle/Utils/Markdown.php
Q |	A
---------|---------
Bug fix? |	yes
New feature? |	no
BC breaks?	| no
Deprecations? |	no
Tests pass? |	yes
Fixed tickets |	#133 
License |	MIT
Doc | PR
> fix #133 XSS injection (with Htmlpurifier)

- src/AppBundle/Command/AddUserCommand.php
- src/AppBundle/Command/ListUsersCommand.php
- src/AppBundle/DataFixtures/ORM/LoadFixtures.php
- src/AppBundle/Entity/User.php
- src/AppBundle/Form/CommentType.php
- src/AppBundle/Form/PostType.php
- src/AppBundle/Twig/AppExtension.php
- src/AppBundle/Twig/LocaleExtension.php
- src/AppBundle/Twig/SourceCodeExtension.php
See https://github.com/symfony/symfony-demo/pull/150
> Add {@inheritdoc} tags where it's needed

- app/Resources/translations/messages.pt_BR.xliff
Sync with changes introduced by #160
> Update Brazilian Portuguese translation

- app/Resources/translations/messages.uk.xliff
In addition to https://github.com/symfony/symfony-demo/pull/158
> Update uk translations for flash messages

- app/config/services.yml
add bundle name prefix 'app.' into the post_repository service ID
> add bundle name prefix to the repository service ID

- app/SymfonyRequirements.php
- app/check.php
- composer.lock
> Updated the app to Symfony 2.7.4

- src/AppBundle/Repository/PostRepository.php
Add missing method doc comments
> Add missing document comment on PostRepository

- src/AppBundle/Twig/SourceCodeExtension.php
The additional complexity is low (just about getting the callable reflector, and this logic is not new as we already have it in Symfony). And the benefit of supporting it is that it shows that a controller can be any callable in Symfony, not only a class method (even though our own controllers are all class methods). This covers other cases:
- functions
- invokable objects (supported in Symfony both for class names and for services, even though there is a bug for the case of class names where it would not inject the container properly in it. PR is coming)
- closures (even though this cannot be used in the fullstack frameworks when specifying the controller in the routing because we cannot dump it, but a special controller resolver or a kernel.controller listener changing the controller …
> Add support for non-method callables in the source code extension

- src/AppBundle/Form/PostType.php
Perhaps it would be good to suggest to the user where to begin writing the post.
> set the focus on title when creating or editing a post

- app/Resources/views/blog/_comment_form.html.twig
> Render global errors of comment form

- app/Resources/translations/messages.uk.xliff
Add UK translations for modal popup
> Add missing Ukrainian translations

- app/Resources/translations/messages.ru.xliff
Add RU translation for modal popup
> Add missing Russian translations

- src/CodeExplorerBundle/Twig/SourceCodeExtension.php
> Fixed #225 unused local variable

- app/Resources/translations/messages.ru.xliff
According to https://github.com/symfony/symfony-demo/pull/233
> Add missing Russian pagination control translation

- app/Resources/translations/messages.uk.xliff
According to https://github.com/symfony/symfony-demo/pull/233
> Add Ukrainian pagination control translations

- app/config/routing.yml
- app/config/services.yml
- src/CodeExplorerBundle/Resources/config/services.yml
> Fix invalid YAML format

- composer.lock
Fix some security issues and other bugs. List of the most important changes: http://symfony.com/blog/symfony-2-7-7-released
> Update Symfony to v2.7.7 with depedendencies

- src/AppBundle/Controller/BlogController.php
> Remove unnecessary namespace usage for Intl class

- app/Resources/translations/messages.ca.xliff
> Added Catalan translation

- app/Resources/translations/messages.ru.xliff
Add missing `label.save_and_create_new` translation in `messages.ru.xliff`
> Add missing ru translation

- app/Resources/translations/messages.pl.xliff
Polish translations for `previous`, `next`, and `save and create new`.
> Added Polish translations

- src/AppBundle/Utils/Markdown.php
> Disable HTMLPurifier caching

- app/Resources/translations/messages.uk.xliff
> Translate HTTP error pages to Ukrainian lang

- app/Resources/translations/messages.ru.xliff
> Translate HTTP error pages to Russian lang

- app/Resources/translations/messages.uk.xliff
I'm sorry, it's my fault! I missed it in https://github.com/symfony/symfony-demo/pull/284 :(
> Fix invalid xliff for Ukrainian translation

- composer.lock
According to [symfony-2-8-2-released](http://symfony.com/blog/symfony-2-8-2-released).
> Update Symfony up to 2.8.2 with few dependencies

- web/app.php
> Request::enableHttpMethodParameterOverride for AppCache

- src/AppBundle/Entity/Post.php
> Undo setting Post to null on comment removal

- README.md
Minor changes in the README.md
> Move Heroku deploy button to the installation section

- src/AppBundle/Controller/Admin/BlogController.php
- src/AppBundle/Controller/BlogController.php
- src/AppBundle/Controller/SecurityController.php
For now the paginator returns an empty array when requested page is out of range. I think we should handle this situation manually and throw the 404 exception. See https://github.com/KnpLabs/knp-components/issues/78
Also, route definition accepts 0 as page parameter and paginator throws an exception.
> Improve routes and fix bug with pagination

- app/config/config_prod.yml
Partially revert https://github.com/symfony/symfony-demo/pull/311 .
According to the https://github.com/symfony/symfony-standard/pull/949 .
> Revert serializer name in config_prod.yml

- app/SymfonyRequirements.php
- composer.lock
- web/config.php
Tweak `config.php` file a bit to be more consistent with the original script.
> Update dependencies according to Symfony v2.8.4 release

- src/CodeExplorerBundle/Twig/SourceCodeExtension.php
> Make the retrieval of template source compatible with Twig 2

- app/Resources/translations/messages.sl.xliff
- app/Resources/translations/validators.sl.xliff
- app/config/config.yml
This patch adds sl_SI translation. Thanks for considering merging it.
> Slovenian translation

- README.md
Related to 822d19e8bec41ec05dddf2749fa0ab2ca7bc68ab
> Require PHP 5.5 as specified in composer.json

- LICENSE
To be consistent with Symfony [LICENSE](https://github.com/symfony/symfony-standard/blob/master/LICENSE).
> Tweak copyright year in LICENSE

- composer.json
- composer.lock
- src/CodeExplorerBundle/Twig/SourceCodeExtension.php
This reverts the temporary #356 solution thanks to this fix made by Twig 1.25.0 version: https://github.com/twigphp/Twig/issues/2011
> Fixed the way we get the Twig template source

- app.json
> Add note about deploying dev environment to Heroku

- composer.json
- composer.lock
According to the https://github.com/symfony/symfony-standard/blob/3.2/composer.json
> Tweak composer.json according to the latest changes in Symfony SE

- composer.lock
- var/SymfonyRequirements.php
Related to the https://github.com/sensiolabs/SensioDistributionBundle/issues/299
Current version of `sensio/distribution-bundle` with Composer 1.3 throws warnings on composer install/update:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP …
```
> Updated sensio/distribution-bundle dependency to fix loading PHP extensions twice

- composer.lock
- web/config.php
```
- Updating twig/twig (v1.30.0 => v1.31.0)
Checking out ddc9e3e20ee9c0b6908f401ac8353635b750eca7
- Updating symfony/symfony (v3.2.1 => v3.2.2)
Checking out 358c59fd21f9db7fdb465d1e07fba822d9e18e9e
- Removing doctrine/dbal (v2.5.5)
- Installing doctrine/dbal (v2.5.6)
- Removing doctrine/doctrine-bundle (1.6.4)
- Installing doctrine/doctrine-bundle (1.6.6)
- Removing sensio/distribution-bundle (v5.0.17)
- Installing sensio/distribution-bundle (v5.0.18)
- Removing sensio/framework-extra-bundle (v3.0.18)
- Installing sensio/framework-extra-bundle (v3.0.19)
- Removing symfony/monolog-bundle (3.0.1)
- Installing symfony/monolog-bundle (v3.0.3)
- Removing symfony/phpunit-bridge (v3.2.1)
- Installing symfony/phpunit-bridge (v3.2.2)
- Removing swiftmailer/swiftmailer (v5.4.4)
- Installing …
```
> Updated to Symfony 3.2.2

- app/Resources/views/admin/blog/index.html.twig
- web/css/main.css
| Before | After
| --- | ---
| ![before-list](https://cloud.githubusercontent.com/assets/73419/22016048/0fa7bd12-dca5-11e6-9cbd-bb944300fb6e.png) | ![after-list](https://cloud.githubusercontent.com/assets/73419/22016057/1add71a4-dca5-11e6-8e5c-88bdbe187b07.png)
> Tweaked the admin blog index

- .php_cs
Otherwise, my project leaves in dirty state after running the fixer.
> Save CS Fixer's cache file into the "var/" directory

- src/AppBundle/Controller/BlogController.php
I couldn't find a text where this was explicitly mentioned, but the code above seems unconventional with respect to what the documentation shows and the rest of the application code.
Refs:
* http://symfony.com/doc/current/best_practices/forms.html#building-forms
* http://symfony.com/doc/current/best_practices/forms.html#handling-form-submits
* http://symfony.com/doc/current/forms.html#building-the-form
* http://symfony.com/doc/current/forms.html#handling-form-submissions
* https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/Admin/BlogController.php#L75-L93
> Minor refactor to new comment action

- app/Resources/translations/messages.hr.xlf
- app/Resources/translations/validators.hr.xlf
- app/config/config.yml
This patch adds translations for hr_HR locale.
> Croatian (Hrvatski) translation

- src/AppBundle/DataFixtures/ORM/PostFixtures.php
Replace method getRandomPostTiles by getRandomPostTitles
> Fix a minor typo error

- src/AppBundle/Entity/Post.php
- src/AppBundle/Entity/Tag.php
- src/AppBundle/Entity/User.php
I noticed there was no license header in three entity classes
> Add missing licence

- CONTRIBUTING.md
Since #387 Assetic is no longer used to manage assets.
> Remove part related to Assetic which is no longer used

- src/AppBundle/DataFixtures/ORM/UserFixtures.php
> Fix a typo

- app/Resources/translations/messages.es.xlf
> Fixed the XLIFF format of one translation file

- app/Resources/views/admin/blog/_form.html.twig
- app/Resources/views/admin/blog/index.html.twig
- app/Resources/views/admin/blog/new.html.twig
- app/Resources/views/blog/_comment_form.html.twig
- app/Resources/views/blog/_delete_post_confirmation.html.twig
- app/Resources/views/blog/post_show.html.twig
> Add more fancy icons for buttons and links

- app/Resources/translations/messages.sl.xlf
- app/Resources/translations/validators.sl.xlf
This patch updates Slovenian (sl) translation with missing translations. Thank you.
> Update sl translation

- app/config/config.yml
> Configured cache.prefix_seed and added a help note

- tests/AppBundle/Command/AddUserCommandTest.php
This continues #597 according to @stof comment: https://github.com/symfony/symfony-demo/pull/597#issuecomment-310074363
> Exclude some tests on Windows too

- composer.lock
Changelog:
- Updating erusev/parsedown (1.6.2 => 1.6.3)
- Updating ezyang/htmlpurifier (v4.9.2 => v4.9.3)
- Updating symfony/polyfill-apcu (v1.3.0 => v1.4.0)
- Updating symfony/polyfill-mbstring (v1.3.0 => v1.4.0)
- Updating twig/twig (v1.33.2 => v1.34.4)
- Updating twig/extensions (v1.5.0 => v1.5.1)
- Updating symfony/polyfill-util (v1.3.0 => v1.4.0)
- Updating symfony/polyfill-php70 (v1.3.0 => v1.4.0)
- Updating symfony/polyfill-php56 (v1.3.0 => v1.4.0)
- **Updating symfony/symfony (v3.3.0 => v3.3.4)**
- Updating symfony/polyfill-intl-icu (v1.3.0 => v1.4.0)
- Updating symfony/polyfill-php54 (v1.3.0 => v1.4.0)
- Updating phpunit/phpunit (4.8.35 => 4.8.36)
- Updating symfony/phpunit-bridge (v3.3.0 => v3.3.4)
- Updating monolog/monolog (1.22.1 => 1.23.0)
- Updating …
> Updated Symfony to 3.3.4

- appveyor.yml
- composer.json
- composer.lock
- phpunit.xml.dist
Fixes https://github.com/symfony/symfony-demo/issues/611
> update dama/doctrine-test-bundle and other deps to fix build

- bin/console
- public/index.php
See https://github.com/symfony/recipes/pull/156
> Don't use getenv(), use $_SERVER instead

- public/index.php
See https://github.com/symfony/recipes/pull/163
> Default to non-debug in index.php and console

- phpunit.xml.dist
Fix https://github.com/symfony/symfony-demo/pull/627#discussion_r136131993
> Set environment variables comment for test

- config/services.yaml
- src/Controller/Admin/BlogController.php
- src/DataFixtures/ORM/PostFixtures.php
- src/Utils/Slugger.php
- src/Utils/Validator.php
- tests/Utils/SluggerTest.php
and remove useless public service alias.
> Remove container dependency in PostFixtures

- app.json
I have not updated the SYMFONY_LOG one, as the monolog config does not use an env variable anymore for the log output, so it requires more work.
> Update env variables for the heroku deployment

- src/Command/DeleteUserCommand.php
Fixing invalid callable argument.
> Use validator on interactive mode

- composer.json
> Move browser-kit and css-selector to require-dev

- config/packages/framework.yaml
- config/packages/routing.yaml
- config/packages/test/framework.yaml
According to:
* https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/packages/test/framework.yaml#L2
* https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/packages/framework.yaml#L6
* https://github.com/symfony/recipes/blob/master/symfony/routing/3.3/config/packages/routing.yaml#L3
> Changed "null" by "~" in yaml files

- Makefile
* https://github.com/symfony/recipes/commit/058d5079e52a3c2026ffc8b4ea3416c910ba6a4f
* https://github.com/symfony/recipes/commit/b5720314d7a3a34bf0bcbe9fc762af3330ca8915
* https://github.com/symfony/recipes/commit/e1701402303ea99f016b4a0afedf37728f78f397
> Update Makefile with latest changes

- README.md
> Added a help note about tests

- src/Kernel.php
This fixes #635 and updates the kernel according to https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php
> Updated the kernel to the latest Symfony Flex recipe changes

- config/packages/framework.yaml
> Sorted the framework.yaml options as the default Symfony recipe

- src/Entity/User.php
This partially fixes #620 and it's based on #659.
> Use the new "json" type from DBAL 2.6

- app.json
> Fix invalid app.json

- config/packages/framework.yaml
Already configured in `translation.yaml`:
https://github.com/symfony/demo/blob/0f8c19fcc05de37b32e78de2506690049268e77e/config/packages/translation.yaml#L2
> Removing duplicated configuration

- src/Repository/PostRepository.php
- src/Repository/UserRepository.php
Appears this section of the book has been moved to separate page.
> Updates links to docs regarding creating custom Repository Classes.

- composer.json
- composer.lock
- config/services.yaml
- src/DataFixtures/PostFixtures.php
- src/DataFixtures/TagFixtures.php
- src/DataFixtures/UserFixtures.php
:tada: :balloon: :birthday: :gift: :heart: :smiley: 
Also updating to latest changes from recipes.
> Upgrade to Symfony 4.0.0 release

- translations/messages.fr.xlf
- translations/messages.it.xlf
- translations/messages.ja.xlf
Add some missing translations in French 🥖 , Italian :it: and Japanese :jp:
> minor: Update translations

- LICENSE
Following Symfony's practices (see https://github.com/symfony/symfony/pull/25647).
> Updated the license year (for the last time)

- config/packages/translation.yaml
> Remove unnecessary configuration for translations/ directory

- translations/messages.de.xlf
menu.search and post.search_for were missing
> Minor: added missing translations

- composer.lock
- symfony.lock
Changelog:
- Removing symfony/thanks (v1.0.0)
- Removing symfony/profiler-pack (v1.0.3)
- Removing symfony/orm-pack (v1.0.5)
- Updating symfony/flex (v1.0.49 => v1.0.65)
- Updating symfony/console (v4.0.2 => v4.0.3)
- Updating symfony/debug (v4.0.2 => v4.0.3)
- Updating doctrine/inflector (v1.2.0 => v1.3.0)
- Updating doctrine/orm (v2.5.14 => v2.6.0)
- Updating symfony/http-foundation (v4.0.2 => v4.0.3)
- Updating symfony/event-dispatcher (v4.0.2 => v4.0.3)
- Updating symfony/http-kernel (v4.0.2 => v4.0.3)
- Updating symfony/dependency-injection (v4.0.2 => v4.0.3)
- Updating symfony/routing (v4.0.2 => v4.0.3)
- Updating symfony/finder (v4.0.2 => v4.0.3)
- Updating symfony/filesystem (v4.0.2 => v4.0.3)
- Updating symfony/config (v4.0.2 => v4.0.3)
- Updating symfony/cache (v4.0.2 => v4.0.3) …
> Updated dependencies to Symfony 4.0.3

- src/Form/DataTransformer/TagArrayToStringTransformer.php
- src/Form/Type/TagsInputType.php
- src/Repository/TagRepository.php
- tests/Form/DataTransformer/TagArrayToStringTransformerTest.php
This completes throughout the demo that amazing feature that is "Service Entity Repository".
> Add service Tag repository and revamping code

- composer.lock
Changelog:
- Updating symfony/flex (v1.0.53 => v1.0.68)
- Updating doctrine/inflector (v1.2.0 => v1.3.0)
- Updating symfony/polyfill-mbstring (v1.6.0 => v1.7.0)
- Updating symfony/http-foundation (v4.0.2 => v4.0.4)
- Updating symfony/polyfill-php70 (v1.6.0 => v1.7.0)
- Updating symfony/event-dispatcher (v4.0.2 => v4.0.4)
- Updating symfony/debug (v4.0.2 => v4.0.4)
- Updating symfony/http-kernel (v4.0.2 => v4.0.4)
- Updating symfony/dependency-injection (v4.0.2 => v4.0.4)
- Updating symfony/routing (v4.0.2 => v4.0.4)
- Updating symfony/finder (v4.0.2 => v4.0.4)
- Updating symfony/filesystem (v4.0.2 => v4.0.4)
- Updating symfony/config (v4.0.2 => v4.0.4)
- Updating symfony/cache (v4.0.2 => v4.0.4)
- Updating symfony/polyfill-apcu (v1.6.0 => v1.7.0)
- Updating symfony/framework-bundle …
> Updated dependencies to Symfony 4.0.4

- src/Controller/Admin/BlogController.php
- src/Controller/BlogController.php
> remove the deprecated sensio/framework-extra-bundle @Method annotations

- composer.json
- composer.lock
- symfony.lock
> Removed symfony/polyfill-apcu dependency

- config/services.yaml
- translations/messages.bg.xlf
- translations/validators.bg.xlf
Added bulgarian language to translations.
> Add Bulgarian language

- composer.json
- composer.lock
- config/bundles.php
- symfony.lock
This is the same PR as #738 created by @ptrm04. The original PR has conflicts in `composer.*` files and those are always hard to solve.
> Moved Doctrine Fixtures bundle to dev and test only

- src/Controller/BlogController.php
- src/Repository/PostRepository.php
- templates/blog/_post_tags.html.twig
- templates/blog/_rss.html.twig
- templates/blog/index.html.twig
Fixes #762
Even though this PR doesn't show any new Symfony feature, it makes the post tags have some sense.
> Filter posts by selected tag

- src/Controller/Admin/BlogController.php
- src/Controller/UserController.php
As suggested by @stof and requested with #870 !
> Migrate from @Security to @IsGranted

- src/Controller/Admin/BlogController.php
Not really important, but replacing one but the alternative don't produce the same result :+1:
> Fixed exemple in alternative use of isGranted annotation

- bin/phpunit
> Removed an unneeded hack for Symfony 4.2

- .travis.yml
As suggested by @fabpot, here: https://twitter.com/fabpot/status/1067085006542118913 😇
> update security check endpoint to security.symfony.com

- src/Form/CommentType.php
- src/Form/PostType.php
- translations/messages+intl-icu.en.xlf
- translations/messages+intl-icu.fr.xlf
This PR add EN and FR translations for inputs help for Post and Comment Form.
> Add translations for input help

- composer.lock
> Update Composer deps

- composer.lock
- yarn.lock
> Update dependencies due to security issues

- src/Entity/Comment.php
- src/Entity/Post.php
- src/Entity/Tag.php
- src/Entity/User.php
For example:
```php
$post = new Post();
// ...
if (!$post->getAuthor()) { // it's null initially so it should be fine allow null return
// ...
} 
// ...
$post->setAuthor(null);
// shouldn't be allowed since the column is not null -> on flush() it'll fail anyway
```
Also it's consistent with `make:entity` command.
> Improving entities contracts

- translations/messages+intl-icu.ru.xlf
> Fixed ru translation

- templates/default/_flash_messages.html.twig
Reverted the handling of flash messages
> Reverted the handling of flash messages

- composer.lock
Hi,
A little PR to fix erusev/parsedown vulnerabilitie
> Fix erusev/parsedown vulnerabilitie

- composer.json
- composer.lock
- config/bundles.php
- symfony.lock
What about to add a maker bundle to this Demo distribution? I think a lot of people are using Demo for some testing, bug reproducing, etc. and have to install it maker bandle themselves - it would be cool to have it installed already. Also, I think it's good to reveal Maker bundle to newcomers as well.
> Add MakerBundle as a dev dependency

- src/Command/AddUserCommand.php
- src/Command/DeleteUserCommand.php
- src/Command/ListUsersCommand.php
Was following the documentation here and one of the links wasn't going anywhere.
Updated the link that wasn't working and also others that had redirects.
Not a big PR, but might help someone.
> Updated docblock links

- README.md
Add a few words about how to work with assets in Symfony Demo, basically to help with questions like #980
> Add development section to explain working with assets

- config/bootstrap.php
See https://github.com/symfony/recipes/pull/611
> Apply latest changes in FWBundle recipe

- composer.json
- composer.lock
- symfony.lock
Fixes https://github.com/symfony/demo/issues/1026
> require symfony/polyfill-intl-messageformatter

- composer.lock
- symfony.lock
Update to Symfony 5.0.1 and latest Symfony Flex version.
> Updated Symfony dependencies

- templates/base.html.twig
> URL updated

- tests/Controller/Admin/BlogControllerTest.php
- tests/Controller/BlogControllerTest.php
- tests/Controller/DefaultControllerTest.php
- tests/Controller/UserControllerTest.php
See https://symfony.com/doc/current/testing/functional_tests_assertions.html
> Use new functional test specific assertions

- src/Controller/Admin/BlogController.php
- src/Controller/BlogController.php
- src/Controller/UserController.php
BTW, short syntax is used in `bin/console debug:router` command's output.
> Use short syntax for routes HTTP methods

- translations/validators+intl-icu.uk.xlf
> Translate 'post.slug_unique' message to Ukrainian

- package.json
> Defined the package.json license

- composer.lock
This updates Symfony to 5.0.8.
> Updated PHP dependencies

- .travis.yml
This PR contains 3 independent commits.
> Travis configuration updates and comments

- composer.lock
- config/packages/security.yaml
- symfony.lock
- tests/bootstrap.php
Everything works fine ... except the login form. When I enter the right credentials at `https://127.0.0.1:8000/en/login`, I'm redirected back to the login form without being authenticated.
@wouterj could you please check if there's something wrong on our side? These are the full logs of the failing login process. Thanks!
```
[2020-05-29T14:02:15.398605+00:00] request.INFO: Matched route "security_login". {"route":"security_login","route_parameters":{"_route":"security_login","_controller":"App\\Controller\\SecurityController::login","_locale":"en"},"request_uri":"https://127.0.0.1:8002/en/login","method":"POST"} []
[2020-05-29T14:02:15.420755+00:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.full_name AS full_name_2, t0.username AS username_3, t0.email AS email_4, t0.password AS password_5, …
```
> Updated to Symfony 5.1 RC2

- src/EventSubscriber/CheckRequirementsSubscriber.php
> fix method name

- src/Controller/BlogController.php
- src/Event/CommentCreatedEvent.php
- src/EventSubscriber/CommentNotificationSubscriber.php
> Rename namespace App\Events to App\Event to be in sync with the docs

- src/Controller/BlogController.php
- templates/blog/index.html.twig
See https://github.com/symfony/demo/issues/1135
> bug #1135 Fix pagination with tag filter

- config/services.yaml
- translations/messages+intl-icu.ar.xlf
- translations/validators+intl-icu.ar.xlf
Symfony framework is used by a huge number of people who speak Arabic and this PR will be helpful for many people!
> Add Arabic language translation

- templates/debug/source_code.html.twig
- templates/default/_flash_messages.html.twig
- translations/messages+intl-icu.ar.xlf
- translations/messages+intl-icu.bg.xlf
- translations/messages+intl-icu.ca.xlf
- translations/messages+intl-icu.cs.xlf
- translations/messages+intl-icu.de.xlf
- translations/messages+intl-icu.en.xlf
- translations/messages+intl-icu.es.xlf
- translations/messages+intl-icu.fr.xlf
- translations/messages+intl-icu.hr.xlf
- translations/messages+intl-icu.id.xlf
- translations/messages+intl-icu.it.xlf
- translations/messages+intl-icu.ja.xlf
- translations/messages+intl-icu.lt.xlf
- translations/messages+intl-icu.nl.xlf
- translations/messages+intl-icu.pl.xlf
- translations/messages+intl-icu.pt_BR.xlf
- translations/messages+intl-icu.ro.xlf
- translations/messages+intl-icu.ru.xlf
- translations/messages+intl-icu.sl.xlf
- translations/messages+intl-icu.tr.xlf
- translations/messages+intl-icu.uk.xlf
- translations/messages+intl-icu.zh_CN.xlf
> Added "Close" Translation

- src/Pagination/Paginator.php
> Make the paginator use the number of posts defined in the Post entity

- composer.lock
> Updated backend dependencies with Composer 2

- .github/workflows/lint.yaml
~~Running `composer update` changes composer.lock~~
Use ramsey/composer-install to cache and install the composer dependencies
> [CI] Use ramsey/composer-install

- composer.json
- composer.lock
- symfony.lock
> Allow PHP 8 and update dependencies

- .github/workflows/lint.yaml
Workaround for https://github.com/doctrine/DoctrineMigrationsBundle/issues/413 and https://github.com/symfony/symfony/issues/39259
> [CI] Lint the container loaded from source instead of xml

- composer.lock
~~I also dumped shivammathur/setup-php to fix the CI macos-latest / PHP 7.3 build~~
~~https://github.com/symfony/demo/runs/2486726663?check_suite_focus=true#step:3:57~~
nvm, seems unrelated
> Bump dependencies to Symfony 5.2.7

- .github/workflows/tests.yaml
This nice idea was suggested by @stof in https://github.com/symfony/demo/pull/1216#issuecomment-844956114 It's much better. Thanks!
> Make GitHub test config easier to maintain

- translations/messages+intl-icu.de.xlf
- Sort entries so that they match the order in the English translation
- Improve some translations
- Add missing translations
> Update German translation

- README.md
Update README, according to v2 change (see `composer.json`)
> doc: v2 use PHP 8.0

- composer.json
- composer.lock
- symfony.lock
Ref https://packagist.org/packages/league/commonmark/stats VS https://packagist.org/packages/erusev/parsedown/stats
> Swap markdown package from erusev to league

- src/Command/AddUserCommand.php
- src/Command/DeleteUserCommand.php
- src/Command/ListUsersCommand.php
Let's leverage one of the best new features of PHP.
> Use indented heredoc/nowdoc

- composer.json
- composer.lock
> Upgrading symfony/flex from v1.17.6 to v2.0.1

- composer.lock
Just a bare update
Ref https://symfony.com/blog/symfony-6-0-1-released
> Update Symfony packages to v6.0.1

- src/Controller/SecurityController.php
Fixes https://github.com/symfony/demo/pull/1269#discussion_r757982860
> Remove unused parameter

- src/Command/DeleteUserCommand.php
I found no example of log inside the demo app, I think it could be wise to showcase it
Ref https://symfony.com/doc/current/index.html in the `The Basics` toc
> Add example and documentation of logging

- LICENSE
- README.md
- Update links in README.md
- Update license year
> Update links & license year

- README.md
I think it is a nice addition here to add such reference
Ref https://symfony.com/blog/a-week-of-symfony-790-14-20-february-2022
> Propose to add a reference link to Symfony book

- composer.json
- composer.lock
See https://github.com/dmaicher/doctrine-test-bundle/releases/tag/v7.0.0
> bump dama/doctrine-test-bundle to ^7.0

- phpstan-baseline.neon
- src/Twig/SourceCodeExtension.php
The original author of this fix is @dkarlovi, who kindly provided the solution in https://github.com/javiereguiluz/demo/pull/1/files
Thanks!
> Fix issue reported by PHPStan

- src/Form/PostType.php
> Post slug is no longer overridden

- translations/messages+intl-icu.ar.xlf
I'm not an Arabic speaker. I just fixed the format. Feel free to suggest the translation.
This PR will fix #1345 .
> Fix `ar` translation issue

- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
> Add permissions to the GitHub Actions workflows

- src/Entity/Comment.php
- src/Entity/Post.php
- src/Entity/Tag.php
- src/Entity/User.php
Benefit built int Doctrine Types directly on each entity
> Use Doctrine Types in entities

- .github/workflows/tests.yaml
Fixes _https://github.com/symfony/demo/issues/1347#issuecomment-1348751078_
> Use 'composer install' instead of 'composer update'

- config/services.yaml
- translations/messages+intl-icu.eu.xlf
- translations/validators+intl-icu.eu.xlf
Basque XLIFF language files added, and config.yml updated.
> Add Basque language translation

- LICENSE
Is there a better way? E.g. write it as `2015+` to avoid changing it every year?
> Update copyrights year in LICENSE

- composer.lock
- src/Entity/Comment.php
- src/Twig/SourceCodeExtension.php
- tests/Controller/Admin/BlogControllerTest.php
- tests/Controller/BlogControllerTest.php
- tests/Controller/UserControllerTest.php
Updates dependencies (including security patches) + fixes the failing tests
> update dependencies + fix tests

- templates/bundles/TwigBundle/Exception/error500.html.twig
Reverts https://github.com/symfony/demo/pull/909
> Remove broken link from the error 500 page

- templates/base.html.twig
This is mostly to update the icon of ~Twitter~ X.
> Update some icons in the footer

- .devcontainer/devcontainer.json
> Update devcontainer.json to use PHP 8.2

- config/services.yaml
- translations/messages+intl-icu.sq.xlf
- translations/validators+intl-icu.sq.xlf
Albanian XLIFF language files added, and config.yml updated.
> Albanian translation

- config/services.yaml
- translations/messages+intl-icu.ne.xlf
- translations/validators+intl-icu.ne.xlf
> Nepali Language Translations

- config/packages/doctrine.yaml
> explicitly configure a default value that will change

- config/services.yaml
- translations/messages+intl-icu.vi.xlf
- translations/validators+intl-icu.vi.xlf
Hello,
This is "Vietnam" language translation.
> add vietnamese translation

- config/packages/framework.yaml
As per IDE suggestion, the of is not needed or rather not good here.
> Grammar fix

- config/packages/security.yaml
> remove invalid access control rule

- assets/styles/bootswatch/_bootswatch.scss
- assets/styles/bootswatch/_variables.scss
> Update to Bootswatch Flatly 5.3.3

- composer.lock
> install security patches
