src/AppBundle/Tests/Utils/SluggerTest.php
src/AppBundle/Utils/Slugger.php

Hello,
I found the symfony-demo repository and the idea behind is great.
also in the symfony best practices, the slugger has 2 problems in my opinion.
* several dashes like lorem--ipsum
* dashes at the begin or end like -lorem-ipsum-
here is my litte pull request.
sebastian

Optimized slugger: trimming dash at the beginning & end and removed doubles dashes

---

src/AppBundle/Utils/Slugger.php

After https://github.com/symfony/symfony-demo/pull/15, the inner `trim()` call is no longer required as the outer one already trims all dashes.

Remove redundant function call

---

app/Resources/views/default/_source_code.html.twig
src/AppBundle/Twig/SourceCodeExtension.php

The source code of the controller cannot be considered as being safe HTML. It needs to be escaped.
This also moves the escaping of the template source code from the extension to the template rendering it, where it belongs (which also avoid using ``|raw``, which is flagged by Insight as being dangerous because it expects the escaping to happen elsewhere, see the first point about the controller source code)

Fix the escaping of the source code when displaying it

---

app/Resources/assets/scss/main.scss
app/Resources/views/admin/blog/index.html.twig
web/css/app.css

I was playing with the Russian translation kindly provided by @bocharsky-bw and I noticed the following issue:
After this PR, the actions should always be correctly displayed:

Fixed backend design for the listing actions

---

src/AppBundle/Controller/SecurityController.php

The assigned Request instance is currently not needed in the login action and thus should be removed from the methods signature.

Removed unneeded Request argument

---

app/config/security.yml

Although `http://symfony.com/doc/current/cookbook/security/form_login.html` is a valid url, I think `http://symfony.com/doc/current/cookbook/security/form_login_setup.html` is more applicable here.

Change URL to login form documentation

---

src/AppBundle/Entity/Comment.php

Assert annotation on $content property was written in lowercase.

small typo fix ;)

---

src/AppBundle/EventListener/ControllerListener.php

There is a more convenient way to check whether the current request is a master request. See http://api.symfony.com/2.7/Symfony/Component/HttpKernel/Event/KernelEvent.html#method_isMasterRequest

Improve the checking if the current request is a master request in the ControllerListener.

---

src/AppBundle/Form/CommentType.php
src/AppBundle/Form/PostType.php

Best Practice
http://symfony.com/doc/current/best_practices/forms.html#custom-form-field-types

Add the app_ prefix to  form field types to avoid collisions

---

app/config/routing.yml

Add locale to `homepage` route to avoid locale resetting on homepage

Fix homepage locale resetting

---

app/config/services.yml

Thanks to stof in https://github.com/symfony/symfony-demo/pull/104#discussion_r35083734

Make Twig services and event listeners private

---

composer.json
composer.lock

New projects generated by the installer suffer from this issue because of https://github.com/sensiolabs/SensioDistributionBundle/issues/215 (see https://github.com/symfony/symfony-installer/issues/110).
this cleans the composer.json of this project.

Remove the broken composer script for root-package install

---

app/Resources/translations/messages.ro.xliff
app/Resources/translations/validators.ro.xliff

Romanian translations based on #80

Romanian translation

---

app/Resources/translations/validators.en.xliff
src/AppBundle/Entity/Post.php

Post content field is not nullable, so we have to validate against NotBlank constraint.
Sadly, this validation message misses now all other translations... Will need others to fix that afterwards, I guess.

Fixing post content constraint

---

app/config/routing.yml

Allow only availiable locales for `_locale` parameter in `homepage` route

Add requirements for _locale parameter on homepage

---

app/config/config.yml
app/config/services.yml

I think better to move this parameter to `app/config/config.yml` assuming that we added there parameters which independent of environment to locate them in one place.

Move independent of env parameter to config.yml

---

src/AppBundle/Controller/BlogController.php

We already create it in [AppBundle\Entity\Comment::__construct](https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Entity/Comment.php#L70)

Remove published date creation repeatedly

---

src/AppBundle/Repository/PostRepository.php

The `select` and `from` methods are optional

Replace query builder with DQL

---

src/CodeExplorerBundle/EventListener/ControllerListener.php
src/CodeExplorerBundle/Resources/config/services.yml
src/CodeExplorerBundle/Twig/SourceCodeExtension.php

Latest Twig versions allow to get the source from the Twig_Template object itself, making it work with any loader (and without needing the loader).
I also switched to private visibility in the CodeExplorerBundle according to the coding standards.

Update the way to retrieve the template source

---

src/CodeExplorerBundle/Twig/SourceCodeExtension.php

The goal is to avoid letting people think that this is the generic way to access the file storing a template, because it is not.

Add a comment describing the code explorer shortcoming

---

app/Resources/translations/messages.en.xliff

This way, the English translation file can be used as a reference to
find missing translations in all other languages.

Add all translatable strings in the English translation file

---

app/Resources/translations/messages.uk.xliff

Add missing `label.save_and_create_new` for Ukrainian translation

Add missing Ukrainian translation

---

app/Resources/views/admin/blog/new.html.twig

We don't need to translate form labels, it happens automatically - otherwise we get a "Missing messages" notice in debug toolbar.

Fix invalid translation key for label name

---

app/config/config.yml

Fix next error after update to the Symfony 3:
> Unknown "asset" function in twig template
P.S. following [v3.0.0-BETA1](https://github.com/symfony/symfony-standard/blob/51ca575c8f1339e62edb077f4f5e0ff1f5566423/app/config/config.yml#L34) release

Include asset Twig function for Symfony 3

---

app/config/security.yml

The `csrf_provider` on a security firewall has been deprecated in favor of `csrf_token_generator` in 2.8 (https://github.com/symfony/symfony/pull/9587).

Use csrf_token_generator instead of deprecated csrf_provider

---

src/AppBundle/EventListener/RedirectToPreferredLocaleListener.php

We have locale dublicates after default locale unshifted to the array of locales on [line 70](https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/EventListener/RedirectToPreferredLocaleListener.php#L70).

Remove locale duplicates in array of locales

---

src/AppBundle/EventListener/RedirectToPreferredLocaleListener.php

If user select `en` language and then go to the homepage - language changing to the preferred language base on user's browser suggestion (see `RedirectToPreferredLocaleListener`). But users don't need this because they already selected `en` for this application.
With this PR I suggest to prevent changing language to the preferred language for referrer requests with the same HTTP host. Thus locale changing will be occured only for `homepage`'s direct requests (`HTTP_REFERER` equal to `null`) or requests from referrers with different HTTP hosts in HTTP_REFERER URL.

Ignore requests from referrers with the same HTTP host

---

app/Resources/TwigBundle/views/Exception/error.html.twig
app/Resources/TwigBundle/views/Exception/error403.html.twig
app/Resources/TwigBundle/views/Exception/error404.html.twig
app/Resources/TwigBundle/views/Exception/error500.html.twig
app/Resources/translations/messages.en.xliff
app/config/routing_dev.yml

We have a translations in this demo app, but error pages do not translate.
For example, when I get some non-existent blog post (`/uk/blog/posts/non-existent-post`) in another lang (except `en`) I should see translated text.

Translate customized error pages

---

app/Resources/views/base.html.twig

See http://symfony.com/blog/new-in-symfony-2-8-dx-improvements#allow-to-check-for-security-even-in-pages-not-covered-by-firewalls

Remove a user instance checking before calling "is_granted"

---

composer.lock

Due to Symfony 2.8.1 [release](http://symfony.com/blog/symfony-2-8-1-released).
List of updated dependencies:
```
- Removing symfony/polyfill-util (v1.0.0)
- Installing symfony/polyfill-util (v1.0.1)
- Removing paragonie/random_compat (1.1.1)
- Installing paragonie/random_compat (1.1.4)
- Removing symfony/polyfill-php70 (v1.0.0)
- Installing symfony/polyfill-php70 (v1.0.1)
- Removing symfony/polyfill-php56 (v1.0.0)
- Installing symfony/polyfill-php56 (v1.0.1)
- Removing symfony/polyfill-php55 (v1.0.0)
- Installing symfony/polyfill-php55 (v1.0.1)
- Removing symfony/polyfill-php54 (v1.0.0)
- Installing symfony/polyfill-php54 (v1.0.1)
- Removing symfony/polyfill-mbstring (v1.0.0)
- Installing symfony/polyfill-mbstring (v1.0.1)
- Removing symfony/symfony (v2.8.0)
- Installing symfony/symfony …
```

Update Symfony up to latest 2.8.1 and other dependencies

---

app/config/routing_dev.yml

What about to add `_locale` parameter in HTTP error route prefix in order to test HTTP error pages with different locales?

Add ability to test HTTP error pages with different locales

---

.travis.yml

Travis use the old Composer's version by default

Update Composer before dependencies installation

---

app/config/config_prod.yml

According to the https://github.com/symfony/symfony-standard/pull/901 .

Use non-deprecated APC validator and serializer service names

---

app/config/parameters.yml.dist

Quotes allows avoiding YAML's syntax error after uncommenting.

Wrap MySQL config URL with single quotes

---

app/Resources/views/admin/blog/edit.html.twig
app/Resources/views/default/_flash_messages.html.twig

This PR remove the useless flash partial include in `edit.html.twig` (as it is already included in `base.html.twig`).
I tweaked the flash partial a little to output `<div class="messages">` only if there is really something to display in the flashbag.

Fix minor flash handling

---

src/AppBundle/Controller/BlogController.php

On the public section, when there are no posts and we are on page 1 we should not return a 404 response.
In fact, that case is already handled in the view.

Fix incorrect 404 response

---

app/Resources/views/default/_flash_messages.html.twig

This PR allows iterating over all message types in the flash bag. It discovers an ability to use different alert types which provided out-of-the-box by Bootstrap and even create a custom one with adding our own `alert-*` CSS classes:
The code behind this is:
```php
class BlogController extends Controller
{
public function indexAction()
{
$this->addFlash('success', 'Success message');
$this->addFlash('info', 'Info message');
$this->addFlash('warning', 'Warning message');
$this->addFlash('danger', 'Danger message');
// ...
}
}
```

Iterate over all flash messages in bag

---

app/Resources/views/base.html.twig
app/Resources/views/blog/about.html.twig
composer.json
composer.lock

Made the application work when PHP's intl is not available

---

CONTRIBUTING.md
README.md
app.json
app/Resources/views/security/login.html.twig
app/config/parameters.yml.dist
src/AppBundle/Command/AddUserCommand.php
src/AppBundle/Command/DeleteUserCommand.php
src/AppBundle/Command/ListUsersCommand.php
src/AppBundle/DataFixtures/ORM/LoadFixtures.php

We moved console to the new directory, but forgot about changing it in the comments. This PR fixes it.

Fix console path in the comments

---

app/config/config_prod.yml

According to the https://github.com/symfony/symfony-standard/pull/965

Use cache.adapter.apcu instead of deprecated validator and serializer

---

app/Resources/views/admin/blog/index.html.twig
app/Resources/views/admin/blog/show.html.twig
app/Resources/views/blog/post_show.html.twig

Seems like these were missed in https://github.com/symfony/symfony-demo/pull/344

Fixed other localizeddate usages to work with the Intl component

---

app/Resources/views/blog/post_show.html.twig
app/Resources/views/security/login.html.twig
app/config/security.yml
src/AppBundle/Controller/SecurityController.php

The Security Form login listener will only intercept the request when it's a POST request, otherwise the controller will be executed. Using the same URL makes things a bit easier, removes the need for the weird controller (which is visited, but should not be executed) and makes things similar to other forms.
Related doc tickets:
* https://github.com/symfony/symfony-docs/issues/6126
* https://github.com/symfony/symfony-docs/pull/6143

Use same URL for login form and check

---

app/Resources/views/base.html.twig

Use `https` schema and add trailing slash for the Symfony blog URL to prevent extra redirection.

Tweak Symfony blog URL

---

README.md

We don't need PHP `5.3` note anymore, Symfony Demo already requires `5.5.9`.

Tweak note about fully-featured web server

---

app/config/config.yml

Symfony demo doesn't seem to work out of the box when using the `prod` configuration because the path used by the `prod` and the `dev` configurations are not the same.
%kernel.root_dir%/../var/data/blog.sqlite
vs
%kernel.root_dir%/data/blog.sqlite
Even if it would be better to separate the both two databases in the real life, here is the patch I use to make it work the same way on a local `dev` mode and on a remote shared hosting.

Update doctrine.dbal.path in config.yml

---

app/config/security.yml

As I realized, only `@Security` annotation works in admin `BlogController` for now. Actually, we don't have `/admin` URL, all admin pages are prefixed with a locale.

Add available locales to the admin path in access control

---

app/Resources/views/security/login.html.twig

We lose `Security::LAST_USERNAME` on authorization failure.

Fill default username and password only when it's empty

---

.gitignore
.travis.yml
appveyor.yml
composer.json
composer.lock

This finishes and rebases #365.

Use locked PHPUnit from dependencies

---

app/Resources/translations/messages.sl.xliff

This patch updates Slovenian (sl_SI) translation according to the English.
Thanks for considering merging it.

Update sl translation

---

src/AppBundle/Controller/Admin/BlogController.php

In at least #223 the topic of sorting on the **admin backend** was mentioned. This is the first time I've loaded the demo app in quite awhile and wasn't sure it was working because I didn't realize the new post I had added was going to show up at the bottom of the list. It may not be a problem for everyone but the bottom of the list on my laptop was well past the fold.
I appreciate that we do not need to make this **admin backend** fully completed with pagination and column-by-column sorting and what-not. However, I think it would make sense to have newer posts showing up at the top.

Ensure default Post sort order shows newer Posts first

---

bin/symfony_requirements
composer.lock
var/SymfonyRequirements.php
web/config.php

Full composer update log:
```
- Removing twig/twig (v1.25.0)
- Installing twig/twig (v1.26.1)
- Removing symfony/symfony (v3.1.4)
- Installing symfony/symfony (v3.1.5)
- Removing psr/log (1.0.0)
- Installing psr/log (1.0.1)
- Removing doctrine/dbal (v2.5.4)
- Installing doctrine/dbal (v2.5.5)
- Removing doctrine/orm (v2.5.4)
- Installing doctrine/orm (v2.5.5)
- Removing sensiolabs/security-checker (v3.0.2)
- Installing sensiolabs/security-checker (v4.0.0)
- Removing sensio/distribution-bundle (v5.0.9)
- Installing sensio/distribution-bundle (v5.0.13)
- Removing twig/extensions (v1.3.0)
- Installing twig/extensions (v1.4.0)
- Removing symfony/phpunit-bridge (v3.1.4)
- Installing symfony/phpunit-bridge (v3.1.5)
- Removing phpdocumentor/reflection-docblock (3.1.0)
- Installing …
```

Updated to Symfony 3.1.5

---

app/config/config_dev.yml

Now that Doctrine DBAL 2.5.5 is out, I think we can remove this "hack". Also because the config value is different from the one recommended and commented in the main config, which might confuse people.

Remove obsolete code

---

app/config/parameters.yml.dist

* Short params have been moved at the top of the file because `env(DATABASE_URL)` is too long and hides them
* `env(SYMFONY_LOG)` value is now wrapped in quotes to avoid deprecations
* Simplified `env(SYMFONY_SECRET)` description
* Commented the params related to the mailer (because the mailer is already disabled in the application)

Updated some help notes for parameters.yml.dist

---

src/AppBundle/Controller/BlogController.php

I found $page parameter's type on default routing is different from that of "/page/{page}" routing.
This difference seems not to be reasonable, then I fix it.

Modify default routing parameter on indexAction

---

app/config/config.yml

Related to https://github.com/symfony/symfony/pull/19973

Updated the ide option to use the default open in browser

---

composer.json

Related to the https://github.com/symfony/symfony-standard/pull/1036
However, I think it makes even more sense here since we have already sorted packages in composer.json.

Sort new Composer packages automatically

---

web/app.php
web/app_dev.php

Fix #411
I think this error could be related to the https://github.com/symfony/symfony-standard/pull/1030

Fix error with class redeclaration: Do not load cache files on PHP 7

---

app/Resources/views/form/layout.html.twig
app/config/config.yml

By default [`bootstrap_3_layout.html.twig` template use `glyphicon-` icon when the `form_errors` block is rendered](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig#L259). In this demo app we use font-awesome (`fa-`) icon library, so this PR try to fix that.
| Before | After |
| ---- | ---- |
| ![post-comment-error](https://cloud.githubusercontent.com/assets/2028198/21733360/1098de26-d42c-11e6-92f7-a8f5b54e09b1.png)  | ![post-comment-fixed](https://cloud.githubusercontent.com/assets/2028198/21733425/5fddca46-d42c-11e6-9ede-4e1846aa01f7.png)  |

Use font-awesome icon in "form_errors" block

---

web/css/main.css

A typical problem I see with lots of Bootstrap-based templates is that they look awful in a very specific range of page widths. When the browser window is not too small and not too big, the template constraints the container width too much. This PR tries to fix this.
| Before | After
| --- | ---
| ![before_container](https://cloud.githubusercontent.com/assets/73419/21886280/5ec58cfa-d8bb-11e6-9b00-fb72cfa30ce4.png) | ![after_container](https://cloud.githubusercontent.com/assets/73419/21886283/5ff8869a-d8bb-11e6-80e4-20c87b9fd059.png)

Design tweaks for small screens

---

app/Resources/views/admin/blog/_delete_form.html.twig
app/Resources/views/admin/blog/edit.html.twig
app/Resources/views/admin/blog/show.html.twig
src/AppBundle/Controller/Admin/BlogController.php

Because it's simpler without a SF Form

Do not use a Symfony Form to delete an article

---

app/Resources/translations/messages.en.xlf
app/Resources/views/base.html.twig
app/Resources/views/blog/_rss.html.twig
app/Resources/views/blog/index.html.twig
app/Resources/views/blog/index.xml.twig
app/Resources/views/blog/post_show.html.twig
src/AppBundle/Controller/BlogController.php
tests/AppBundle/Controller/BlogControllerTest.php
web/css/main.css

This try to implement a simple RSS channel accepted in https://github.com/symfony/symfony-demo/issues/155 since Aug 2015.
Knowledge that brings:
* Custom XML extension to specify the format of the template (`index.xml.twig`).
* How to render a simple XML file.
Any suggestions would be welcome! ;)

Add a blog posts RSS channel

---

app/AppKernel.php
app/Resources/translations/messages.en.xlf
app/Resources/views/blog/post_show.html.twig
app/config/config.yml
app/config/config_dev.yml
app/config/parameters.yml.dist
app/config/services.yml
src/AppBundle/Controller/BlogController.php
src/AppBundle/EventListener/CommentNotificationListener.php
src/AppBundle/Events.php

See https://github.com/symfony/symfony-demo/pull/420

Notify post author about new comments by sending email

---

app/Resources/views/admin/blog/index.html.twig
src/AppBundle/Controller/Admin/BlogController.php

We are currently unable to show a post if the logged user is not the author (i.e. in backend).
| Before | After |
| ---- | ---- |
| ![posts-list-before](https://cloud.githubusercontent.com/assets/2028198/21901130/843901d4-d8c4-11e6-84e5-ecdae35854f1.png) | ![posts-list-after](https://cloud.githubusercontent.com/assets/2028198/21901731/e20e3b1a-d8c6-11e6-94e5-dff0f22d6b86.png) |

Simplify the post list (admin) displaying your posts only

---

tests/AppBundle/Controller/Admin/BlogControllerTest.php
tests/AppBundle/Controller/BlogControllerTest.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/AppBundle/Utils/SluggerTest.php

This complements the new tests added in #434.

Added more tests for the backend

---

app/Resources/views/blog/post_show.html.twig
app/config/services.yml
src/AppBundle/Controller/Admin/BlogController.php
src/AppBundle/Security/PostVoter.php

Implement https://github.com/symfony/symfony-demo/issues/440 feature.
Following some references and recommendations in:
- https://symfony.com/doc/current/components/security/authorization.html
- http://symfony.com/doc/current/security/voters.html
- https://stovepipe.systems/post/symfony-security-roles-vs-voters (@iltar blog)
Any suggestion is welcome!

Add a security Post Voter

---

composer.lock

```
- Updating symfony/symfony (v3.2.2 => v3.2.3)
- Updating doctrine/dbal (v2.5.6 => v2.5.11)
- Updating doctrine/doctrine-bundle (1.6.6 => 1.6.7)
- Updating sensio/framework-extra-bundle (v3.0.19 => v3.0.21)
- Updating sebastian/comparator (1.2.2 => 1.2.4)
- Updating phpunit/phpunit (4.8.31 => 4.8.35)
- Updating symfony/phpunit-bridge (v3.2.2 => v3.2.3)
```

Updated dependencies to Symfony 3.2.3

---

src/AppBundle/Entity/Post.php
src/AppBundle/Entity/Tag.php
src/AppBundle/Form/DataTransformer/TagArrayToStringTransformer.php
src/AppBundle/Form/Type/DateTimePickerType.php
src/AppBundle/Form/Type/TagsInputType.php

* Removed unused old `isAuthor()` method from `Post`
* Removed useless PHPDoc
* Add code comments about Tags feature implementation
* Removed setByReference option which is unnecessary now.

Cleanup and comments about Tags feature implementation

---

app/config/security.yml

This PR change the default target path `/` to <del>`admin_index`</del> `blog_index` route, useful when we access to login page directly (i.e. through URL).

By default redirect to post index page after login

---

src/AppBundle/Controller/Admin/BlogController.php

We can't use cascade delete constraint in this case because Foreign key support is not enabled in SQLite by default. (https://www.sqlite.org/foreignkeys.html#fk_enable)
More information about it:
- https://github.com/doctrine/dbal/issues/2104
- https://github.com/doctrine/dbal/issues/1204
So my only one solution was to clear this relations manually.

Delete all post/tag entries on delete a Post

---

app/config/services.yml
src/AppBundle/EventListener/CheckRequirementsSubscriber.php

This finishes #431 by doing some renaming and minor tweaks.

Improved the event subscriber that listens to database exceptions

---

app/Resources/translations/validators.uk.xlf

`{{limit}}` not translated at all.

Fix translating "limit" variable: add extra spaces

---

app/Resources/translations/messages.pl.xlf

There is nothing like "zademonostrowania". It is like english `demonstrate` vs `demonostrate`.

Fixed typo in polish translations

---

src/AppBundle/Command/AddUserCommand.php

We now require PHP 5.5.9 in this app, so there's no need to maintain this code.

Drop support for PHP 5.3 callbacks

---

app/AppKernel.php
app/Resources/views/admin/blog/_delete_form.html.twig
composer.json
composer.lock
phpunit.xml.dist
tests/AppBundle/Controller/Admin/BlogControllerTest.php

This fixes https://github.com/symfony/symfony-demo/issues/445 by using https://github.com/dmaicher/doctrine-test-bundle to have proper test isolation.

Use dama/doctrine-test-bundle for proper test DB isolation

---

app/Resources/translations/validators.ru.xlf

The `post.too_many_tags` key isn't translated

Add missing validation message for Russian

---

composer.json
composer.lock

Empty psr-4 prefixes can force the autoloader to scan the `src/` directory for all namespaces. The best practice is to always make the prefix explicit.
`composer update` also, doing:
```
- Updating twig/twig (v1.31.0 => v1.32.0) Loading from cache
- Updating sensiolabs/security-checker (v4.0.0 => v4.0.1) Loading from cache
- Updating phpunit/php-timer (1.0.8 => 1.0.9) Loading from cache
- Updating phpunit/php-token-stream (1.4.9 => 1.4.11) Loading from cache
```

Fix PSR4 in composer.json, add dump()

---

.travis.yml

Enable php 7.1 in travis-ci matrix.

run tests against php 7.1

---

README.md

Fix #492
In order to match the folder created by Symfony Installer which is `symfony_demo` instead of `symfony-demo`.

Use symfony_demo instead of symfony-demo folder name in docs

---

app/Resources/translations/messages.en.xlf
app/Resources/translations/messages.fr.xlf

Add missing french translations + backport a translation from FR to EN

Add missing french translations

---

composer.lock

```
- Updating ezyang/htmlpurifier (v4.8.0 => v4.9.1)
- Updating twig/twig (v1.31.0 => v1.32.0)
- Updating paragonie/random_compat (v2.0.4 => v2.0.9)
- Updating symfony/symfony (v3.2.3 => v3.2.5)
- Installing ircmaxell/password-compat (v1.0.4)
- Installing symfony/polyfill-php55 (v1.3.0)
- Updating sensio/framework-extra-bundle (v3.0.21 => v3.0.23)
- Updating swiftmailer/swiftmailer (v5.4.5 => v5.4.6)
- Updating symfony/swiftmailer-bundle (v2.4.2 => v2.5.3)
- Updating white-october/pagerfanta-bundle (v1.0.7 => v1.0.8)
- Updating sebastian/recursion-context (1.0.2 => 1.0.5)
- Updating phpunit/php-timer (1.0.8 => 1.0.9)
- Updating phpunit/php-token-stream (1.4.9 => 1.4.11)
- Updating phpspec/prophecy (v1.6.2 => v1.7.0)
- Updating doctrine/dbal (v2.5.11 => v2.5.12)
- Updating …
```

Updated dependencies to Symfony 3.2.5

---

tests/AppBundle/Command/AddUserCommandTest.php

This adds a simple test for `AddUserCommand` that creates a user non-interactively and interactively.
Fixes https://github.com/symfony/symfony-demo/issues/473.

Add a complete test for AddUserCommand

---

tests/AppBundle/Command/AddUserCommandTest.php

This minor php cs error was introduced by commit 774adca218e95d0a68f5ac1d41948dfd927899d2

Fixes a minor php cs error that prevents builds to pass

---

src/AppBundle/Form/DataTransformer/TagArrayToStringTransformer.php
tests/AppBundle/Form/DataTransformer/TagArrayToStringTransformerTest.php

Added some tests to demonstrate how to mock a Repository and test things without the database

New tests, TagArrayToStringTransformer

---

src/AppBundle/DataFixtures/ORM/PostFixtures.php
src/AppBundle/DataFixtures/ORM/TagFixtures.php
tests/AppBundle/Controller/Admin/BlogControllerTest.php
tests/AppBundle/Controller/BlogControllerTest.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/ControllerTestTrait.php
tests/FixturesTrait.php

* Testing new blog post
* Testing show blog post (admin)
* Testing add a comment to post
* Changing some `PostFixtures` methods to static for reusability
* Simplify and reordering some tests

Add more tests to blog post

---

app.json

This allows tests to automatically run in the (currently in beta) Heroku CI service.

app.json "test" script for Heroku CI

---

app/Resources/translations/messages.en.xlf
app/Resources/views/admin/blog/edit.html.twig

I propose to add a new button "show post" to review quickly the edited post, it avoid come back to post list for perform this common action.
I think it's more an ergonomic issue rather than a new feature.
**Preview:**

Add "show" button on edit post

---

app/Resources/views/admin/blog/_delete_form.html.twig
app/Resources/views/admin/blog/_form.html.twig
app/Resources/views/admin/blog/edit.html.twig
app/Resources/views/admin/blog/index.html.twig
app/Resources/views/admin/blog/new.html.twig
app/Resources/views/admin/blog/show.html.twig
app/Resources/views/base.html.twig
app/Resources/views/blog/_comment_form.html.twig
app/Resources/views/blog/index.html.twig
app/Resources/views/blog/post_show.html.twig

See http://twig.sensiolabs.org/doc/2.x/coding_standards.html:
> Do not put any spaces before and after the opening and the closing of arrays and hashes.
> Put one (and only one) space after the start of a delimiter ({{, {%, and {#) and before the end of a delimiter (}}, %}, and #})
I changed a `{%else%}` to `{% else %}` on this point.

Conform to Twig coding standards

---

app/Resources/translations/messages.es.xlf

Some missing spanish translations discovered by #531 :wink:

Update translations es

---

src/AppBundle/Entity/Comment.php
src/AppBundle/Entity/Post.php
src/AppBundle/Entity/Tag.php
src/AppBundle/Entity/User.php

Updated the DocBlocks of the Entities from consistency point of view.

Updated the DocBlocks of the Entities

---

web/css/main.css

Before, some styles like margin also were applied to the right sidebar elements like `p`, `h3` tags.

Prevent affecting some styles on the right sidebar

---

app/Resources/views/admin/blog/_delete_form.html.twig

Add trash icon for 'Delete post' button

---

src/AppBundle/Entity/Comment.php
src/AppBundle/Entity/Post.php
src/AppBundle/Entity/Tag.php
src/AppBundle/Entity/User.php

This reverts #527
The reasons were described earlier in #394

Revert "Updated the DocBlocks of the Entities from consistency pov"

---

app/Resources/translations/messages.ca.xlf
app/Resources/translations/messages.de.xlf
app/Resources/translations/messages.en.xlf
app/Resources/translations/messages.es.xlf
app/Resources/translations/messages.fr.xlf
app/Resources/translations/messages.it.xlf

Actually, we have the same translation message for `help.login_users` key

Remove title.login_help translation which is unused

---

app/config/security.yml

Update the url's to the documentation in security.yml

Update the doc urls

---

.gitignore
.php_cs.dist

Hello,
Everything is in the title.
I also removed the shebang because it looked useless, let me know if I am wrong :-)

Rename .php_cs to .php_cs.dist as a best practise

---

app/Resources/translations/messages.pt_BR.xlf

Brazilian Portuguese (pt_BR) translation updated

---

src/AppBundle/Entity/Post.php

It's an edge case, but what do you think about always updating inverse side in adder/remover methods?
For example, currently this code won't update inverse side properly:
```php
$comment = new Comment();
$post->getComments()->add($comment);
// but then if we will call adder method
$post->addComment($comment); // Comment::$post is still equals null here due to the failed `!contains()` check in it
```

RFC: Always enforce updating inverse side for Comment

---

.travis.yml

Following the decision of Symfony to drop HHVM support.

Removed HHVM from Travis CI test matrix

---

app/config/config.yml
app/config/config_dev.yml
app/config/config_test.yml
app/config/parameters.yml.dist
src/CodeExplorerBundle/Resources/config/services.yml
src/CodeExplorerBundle/Twig/SourceCodeExtension.php

As explained in https://symfony.com/blog/new-in-symfony-3-3-a-simpler-way-to-get-the-project-root-directory

Replaced kernel.root_dir by kernel.project_dir

---

src/AppBundle/Twig/AppExtension.php
src/CodeExplorerBundle/Twig/SourceCodeExtension.php

```
/**
* Returns the name of the extension.
*
* @return string The extension name
*
* @deprecated since 1.26 (to be removed in 2.0), not used anymore internally
*/
function getName();
```

Removed the deprecated getName() method in Twig extensions

---

src/AppBundle/Command/AddUserCommand.php
src/AppBundle/EventListener/CheckRequirementsSubscriber.php

Relates to https://github.com/symfony/symfony/issues/22951 + use `ConsoleEvents::ERROR` rather than `ConsoleEvents::EXCEPTION`

Fix autowiring type deprec & use ConsoleEvents::ERROR

---

src/AppBundle/EventListener/CheckRequirementsSubscriber.php

Fixes an issue when there isn't any command yet and an error was triggered. For instance, when trying to use a non-existing command.
> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getName() on null in src/AppBundle/EventListener/CheckRequirementsSubscriber.php:70

Fix console error listener when there is no command yet

---

app/config/config_test.yml
phpunit.xml.dist

This approach is more flexible than we used in #572

Override DATABASE_URL by setting default parameter's value

---

app/config/config.yml
app/config/config_dev.yml
app/config/config_prod.yml
app/config/parameters.yml.dist

to match the standard edition configuration, which is way more convenient.
In dev, it'll now log every debug information but events, console errors are now logged natively and we don't need them to be output on stderr (we already have the stacktrace when running the console), and the `server:log` command allows to see logs in real-time.

Update logs configuration

---

app/config/services.yml

Fixes current exception:
```php
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]         
You have requested a non-existent service "slugger". Did you mean this: "logger"?  
```
`ContainerAwareInterface` still is the way to access services inside fixture loaders. Maybe something could be done on the doctrine-fixtures-bundle side, but for now we need to have a public alias for this service.
We could also exclude the `DataFixtures\ORM` folder from PSR-4 loading, but it's probably not worth it and may "overwhelm" a little newcomers:
```diff
-        exclude: '../../src/AppBundle/{Controller,Entity,Repository}'
+        exclude: '../../src/AppBundle/{Controller,Entity,Repository,DataFixtures/ORM}'
```

Alias the slugger to fix fixtures loading

---

src/AppBundle/Form/Type/DateTimePickerType.php
webpack.config.js

This resolves #591 if someone else can confirm the same error.
The `admin.js` file size in production increases to `227k` (from `178k`)
The locale list comes from `config.yml`:
```yaml
parameters:
app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN
```

[Webpack/Moment] Include all moment locales

---

src/CodeExplorerBundle/EventListener/ControllerListener.php
src/CodeExplorerBundle/Resources/config/services.yml

Since 3.3, [listeners do not have to be public anymore](https://github.com/symfony/symfony/pull/20953/files#diff-8604f72b4ae78c6c364c1af8c1dee17cL63).
I also believe declaring services private by default by adding `_defaults: { public: false }` on top will become a best practice, so I think we should use it in the CodeExplorerBundle.
Actually, we could also use classnamed services, autoconfigure and autowiring, but at least for the last one, I think we should keep a place in this application where services are declared entirely manually (autoconfigure is debatable this way too, that's true).
WDYT?

Use 3.3 DI features in CodeExplorerBundle

---

tests/AppBundle/Command/AddUserCommandTest.php

Skip tests that require stty when it's not available

---

app/config/services.yml

So it's clear it's name of the filter and not English.
I was about to send PR with space "localized date", but then I've read the "filter". So I hope this is the correct option :)

services: added name to the quote

---

.travis.yml
composer.json
composer.lock

We discussed about this in the past. I think it's better this way because using PHPUnit Bridge instead of PHPUnit is the recommended way (as explained in the Symfony Docs).

Removed PHPUnit as a dependency and rely on PHPUnit Bridge

---

composer.lock

Updated dependencies:
- **Updating symfony/symfony (v3.3.4 => v3.3.5):  Checking out b9a0d3d239**
- Updating friendsofphp/php-cs-fixer (v2.2.4 => v2.2.5): Downloading (100%)
- Updating sensio/generator-bundle (v3.1.4 => v3.1.6): Loading from cache
- Updating symfony/phpunit-bridge (v3.3.4 => v3.3.5): Loading from cache

Update dependencies to fix CVE-2017-11365 empty pass validation issue

---

.env.dist
src/Kernel.php

Setting `DATABASE_URL=sqlite:///var/data/blog.sqlite` as default, causes this known error through `index.php`:
```
An exception occurred in driver: SQLSTATE[HY000] [14] unable to open database file
```
So the right relative path in this case should be `sqlite:///../var/data/blog.sqlite` BUT then it wouldn't work for `bin/console` entries. Then, relative paths shouldn't be the right way but absolute paths.
The right thing is that soon (in 3.4 & 4.0) we can use environment variables with configuration parameters https://github.com/symfony/symfony/pull/23901, so the final configuration would be the one proposed. For now a workaround to make both scenarios work `index.php` and `bin/console`.

Workaround to use DATABASE_URL with %kernel.project_dir% parameter

---

config/packages/test/doctrine.yaml
phpunit.xml.dist

We can configure the test database file in `phpunit.xml.dist` and keep it simple.

Remove forced configuration for tests environment

---

tests/Form/DataTransformer/TagArrayToStringTransformerTest.php
tests/Utils/SluggerTest.php
tests/Utils/ValidatorTest.php

Moving on to the most recent updates.

Using the new PHPUnit namespace

---

src/Twig/AppExtension.php
src/Twig/SourceCodeExtension.php

Moving on to the latest changes...

Using the new Twig namespace

---

src/Command/AddUserCommand.php
src/Command/DeleteUserCommand.php

After https://github.com/symfony/symfony-demo/commit/5180bdcce3bac08e59ba9b5d34fbd7c2b007f7e3

Remove useless constants in commands

---

.travis.yml
composer.lock

This performs validation of the composer metadata to ensure they are valid:
- composer.json does not contain any error
- composer.json does not trigger any warning (thanks to the strict mode)
- composer.lock is uptodate

Add validation of the composer files on Travis

---

appveyor.yml

On windows, composer does not use a symlink when installing binaries but creates a proxy script instead. This proxy is not a PHP script, so running it through PHP does not work.
The goal of composer is to allow running the script in a way similar to the Linux usage relying on shebangs.
So tests were not running on AppVeyor: https://ci.appveyor.com/project/fabpot/symfony-demo/build/1.0.1088#L140

Fix the CI on Appveyor

---

src/Command/AddUserCommand.php

Fixing password validation in `AddUserCommand`.
added type hint to `$io`-var enabling IDE completion to prevent things like that in future changes

Fixing add user password validation

---

README.md

Hi
Seems that symfony-demo in no longer available for php 5.5.9.
Composer.json define the minimum requirement to 7.1.3.
Readme update

Update php version requirement in readme

---

composer.json
composer.lock
phpunit.xml.dist

Updates to latest version of `dama/doctrine-test-bundle` which uses the same listener class for PHPUnit 5 and 6+.

update dama/doctrine-test-bundle to ^4.0

---

src/Controller/BlogController.php

I don't like how `dump()` is explained. Some newcomers may think that you need to do the `if ('dev' === $this->getParameter('kernel.environment')) {` check yourself when using this function. I propose to change it like this pull request ... or even remove it entirely. Thoughts?

Tweaked the way dump() function is explained

---

translations/messages.sl.xlf

Hello, this patch updates Slovenian (sl_SI) translations according to the current English upstream version.

Update Slovenian translations

---

composer.json

When using the demo, people should get a new project id instead of a generic one.

Remove the project ID, which should be different per project

---

src/Command/AddUserCommand.php
src/Command/DeleteUserCommand.php
src/Utils/Validator.php

This is only a minor improvement that remove the short trace line where the exception was thrown, thus the output feels like a natural message (intentional) rather than an (unexpected) debuggeable error:
**before**
**after**
In general, by using the exception classes of the Console component should be better for user messages.

[UX] Friendly command exceptions output

---

composer.json
composer.lock
config/services.yaml
src/Command/AddUserCommand.php
src/Command/DeleteUserCommand.php
src/Command/ListUsersCommand.php
src/Controller/Admin/BlogController.php
src/Controller/BlogController.php
src/Repository/PostRepository.php
src/Repository/UserRepository.php
tests/Command/AddUserCommandTest.php

Living in the edge of the [new awesome features like this](https://github.com/doctrine/DoctrineBundle/pull/727), I'm proposing before doctrine-bundle 1.8 release, show/test this great feature that simplify our lives and to see how it works! and because soon, best practices should adopt this approach by default. (In fact [maker-bundle will do it](https://github.com/symfony/maker-bundle/blob/master/src/Resources/skeleton/doctrine/Repository.php.txt) <3)
What do you think?

Make Doctrine repository as service and autowire/use it anywhere

---

config/services.yaml

This configuration is only necessary for service controllers that don't extend from `Controller` or `AbstractController`, which is not the case here.
It is not clear in the recipe (in this sense) but the documentation is clear enough:
> http://symfony.com/doc/current/controller.html#fetching-services-as-controller-arguments
> If you're not using the default configuration, you can tag your service manually with `controller.service_arguments`.

Remove unnecessary configuration for controllers

---

composer.json
composer.lock

This dependency is implicitly provided by `symfony/orm-pack`.

Removes explicit dependency on DoctrineBundle.

---

.travis.yml

Runs `doctrine:schema:validate` command with database sync skipping and
no interaction flags.
This is what I usually setup in CI for my projects to avoid common Doctrine's mapping errors e.g. missing `inversedBy` properties.

Adds Doctrine's mapping validation on Travis.

---

translations/validators.pl.xlf

Small fix on PL validators translation to support message declension.
Done in the same way as it was done in CS validators translation.
P.S. I've closed previous PR because I've used wrong account. Sorry for the problem.

[Validators PL translation] Fixing declension.

---

templates/form/layout.html.twig

This is consistent with the latest changes in the form themes and avoids any future collision between form view properties and form fields.
See https://github.com/symfony/symfony/pull/25236

Use rootform test to check by root form view

---

src/Controller/Admin/BlogController.php
src/Controller/BlogController.php
src/Controller/SecurityController.php

Related to https://github.com/symfony/symfony/issues/25361.

Use the Route annotation from Symfony core

---

webpack.config.js

`window.jQuery` is already defined in `autoProvidejQuery` function, there's no need to override:
https://github.com/symfony/webpack-encore/blob/v0.9.1/lib/WebpackConfig.js#L271

Removed jQuery from auto provided variables in webpack config

---

composer.lock

List of updated deps:
```
- Updating symfony/asset (v4.0.1 => v4.0.2)
- Updating symfony/cache (v4.0.1 => v4.0.2)
- Updating symfony/expression-language (v4.0.1 => v4.0.2)
- Updating symfony/inflector (v4.0.1 => v4.0.2)
- Updating symfony/property-access (v4.0.1 => v4.0.2)
- Updating symfony/options-resolver (v4.0.1 => v4.0.2)
- Updating symfony/intl (v4.0.1 => v4.0.2)
- Updating symfony/event-dispatcher (v4.0.1 => v4.0.2)
- Updating symfony/form (v4.0.1 => v4.0.2)
- Updating symfony/routing (v4.0.1 => v4.0.2)
- Updating symfony/http-foundation (v4.0.1 => v4.0.2)
- Updating symfony/debug (v4.0.1 => v4.0.2)
- Updating symfony/http-kernel (v4.0.1 => v4.0.2)
- Updating symfony/finder (v4.0.1 => v4.0.2)
- Updating symfony/filesystem (v4.0.1 => v4.0.2)
- Updating symfony/dependency-injection …
```

Update to Symfony 4.0.2 with deps

---

config/packages/test/security.yaml

I learned this cool trick from this @taylorotwell tweet: https://twitter.com/taylorotwell/status/943135617466105856
In my local machine, tests went from 15 to 10 seconds!

Reduce the BCrypt cost in tests to run them much faster

---

src/Repository/PostRepository.php

This fixes #734.
The search engine is now more strict because it's case sensitive (if the post title is `Lorém ipsum`, `lorém` and `Lorem` gives no results; you must search for `Lorém`). I'd say it's OK because we're not building a real search engine. Thoughts?

Allow to search blog posts with unicode characters

---

composer.json
composer.lock

I think you must use twig-bundle directly in require section because it is needed for project to run with composer --no-dev for example. It can easily replace twig dependency because twig bundle depends of twig :)

Use Twig Bundle in require

---

config/services.yaml

In this demo app we always keep config files in sync with those provided by the Symfony recipes. This makes the config easier to understand for newcomers (there will be no surprises because when they install Symfony, they'll get the same config they saw on this app).
In addition, I think it's a good idea to keep the `App\Controller\` config. It's true that technically we don't need it because our controllers extend from the base controller. But having this config explicitly, makes it easier to understand what's going on with the services created from controllers.

Keep the services.yaml file in sync with the default Symfony file

---

translations/messages.nl.xlf
translations/validators.id.xlf
translations/validators.nl.xlf

Spotted thanks to the latest improvement of `lint:xliff`: https://github.com/symfony/symfony/pull/26682

Fixed minor issues in the XLIFF files

---

composer.json

Not needed anymore after symfony/flex#363

Remove default flex id

---

.travis.yml
phpunit.xml.dist

Fixes https://github.com/symfony/demo/issues/811
When running the test suite on php 7.1 the wrong phpunit (non-maintained version 5) is required by the simple-phpunit-bridge which is not compatible with https://github.com/dmaicher/doctrine-test-bundle-demo.

require phpunit 7.1 via SYMFONY_PHPUNIT_VERSION env variable

---

src/Form/CommentType.php
src/Form/PostType.php
templates/blog/_comment_form.html.twig

One of my favourite new Symfony 4.1 features. It's amazing and it looks like this in the Demo app:

Add help messages to some form fields

---

src/Controller/Admin/BlogController.php

Removes a comment that was obsoleted by changing usages of `@Security` to the `@IsGranted` annotation.

Remove outdated comment

---

.php_cs.dist
composer.json
composer.lock
tests/Form/DataTransformer/TagArrayToStringTransformerTest.php

Our code was already good 😎 ... but this rule removed some unneeded PHPdoc.

Enabled the no_superfluous_phpdoc_tags fixer rule

---

templates/security/login.html.twig

This fixes #829 hiding the icon when browsing the site in a smartphone.

Minor design tweak for smartphones

---

src/Command/AddUserCommand.php
src/Command/ListUsersCommand.php
src/Twig/AppExtension.php
tests/Form/DataTransformer/TagArrayToStringTransformerTest.php

A follow-up of #837 after this comment from @stof: https://github.com/symfony/demo/pull/837/files/f8483c27636eafa5a56302ba6daac04dcd36e8fa#r204007113

Added more type hints and removed PHPdoc

---

composer.json
composer.lock

This avoid the following error while installing the demo application with composer 1.7.
```
Declaration of Symfony\Flex\ParallelDownloader::getRemoteContents($originUrl, $fileUrl, $context) should be compatible with Composer\Util\RemoteFilesystem::getRemoteContents
($originUrl, $fileUrl, $context, ?array &$responseHeaders = NULL)
```

Fix installation when using composer 1.7+

---

.travis.yml
composer.lock
symfony.lock

Currently, `composer install` as well as Travis CI fails, because of symfony/http-foundation (v4.1.1): 
https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers
This PR updates the `composer.lock` and `symfony.lock` files to use the latest Symfony 4.1.3. Should also fix Travis breakage on #845.

Updating `.lock` files for security reasons

---

translations/messages.nl.xlf

- Add some missing strings
- Fix archaic and corny translations (formal "u" -> informal "je", etc)

Update dutch language file.

---

.gitignore

A better fix would probably be to move the DB elsewhere.
But at least, this change is required to make the demo work out of the box. If not, the `var/` directory is not added when doing `git add .` after creating the project with `composer create-project`, which is not what we want.

Fix /var configuration in .gitignore

---

templates/default/_flash_messages.html.twig

Use of flash messages triggers session start, which as of last year
triggers Symfony to mark response as private, and not cached.
Fix the issue by checking if there is a session first as advised on:
https://symfony.com/doc/current/session/avoid_session_start.html

Fix session starting issue on flash messages usage

---

templates/default/_flash_messages.html.twig

Fixed the handling of flash messages

---

composer.json
composer.lock
config/packages/dev/debug.yaml
config/packages/security_checker.yaml
config/packages/sensio_framework_extra.yaml
config/packages/test/dama_doctrine_test_bundle.yaml
config/packages/test/monolog.yaml
config/packages/test/routing.yaml
config/packages/validator.yaml
phpunit.xml.dist
public/bundles/whiteoctoberpagerfanta
symfony.lock

As we usually do, now that Symfony 4.2 is in feature freeze, let's update this app to `4.2.x-dev` so we can detect issues/bugs/deprecations early and report to the appropriate repositories.

Updated the app to Symfony 4.2.x-dev

---

src/Controller/Admin/BlogController.php
src/Controller/UserController.php

This is a deprecation introduced by the upgrade to Symfony 4.2 in #865.
```
14x: Using the "has_role()" function in security expressions is deprecated since Symfony 4.2, use "is_granted()" instead.
2x in BlogControllerTest::testAdminNewPost from App\Tests\Controller\Admin
2x in BlogControllerTest::testAdminEditPost from App\Tests\Controller\Admin
2x in BlogControllerTest::testAdminDeletePost from App\Tests\Controller\Admin
2x in UserControllerTest::testAccessDeniedForAnonymousUsers from App\Tests\Controller
2x in UserControllerTest::testEditUser from App\Tests\Controller
2x in UserControllerTest::testChangePassword from App\Tests\Controller
1x in BlogControllerTest::testAdminBackendHomePage from App\Tests\Controller\Admin
1x in BlogControllerTest::testAdminShowPost from …
```

Fixed the has_role() deprecation

---

src/Entity/Comment.php
src/Entity/Post.php

This is a deprecation introduced by the upgrade to Symfony 4.2 in #865.
```
3x: Validating a \DateTimeInterface with "Symfony\Component\Validator\Constraints\DateTime" is deprecated since version 4.2. Use "Symfony\Component\Validator\Constraints\Type" instead or remove the constraint if the underlying model is already type hinted to \DateTimeInterface.
1x in BlogControllerTest::testAdminNewPost from App\Tests\Controller\Admin
1x in BlogControllerTest::testAdminEditPost from App\Tests\Controller\Admin
1x in BlogControllerTest::testNewComment from App\Tests\Controller
```

Fixed the DateTime constraint deprecation

---

tests/Command/AddUserCommandTest.php

This leverages https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing to make it easier to test the command service.

Use testing container to access private service

---

config/packages/framework_extra.yaml

It exists already as https://github.com/symfony/demo/blob/bbe5180a8c3b6886ea59227df83de59a4573e586/config/packages/sensio_framework_extra.yaml

Delete duplicate sensio_framework_extra config

---

bin/console

See https://github.com/symfony/recipes/pull/479

Remove deprecated --env and --no-debug console options

---

templates/blog/index.html.twig

The description says that neither HTML nor Markdown is allowed. This is also the only place where markdown is interpreted on the summary.

removed md2html from summary on blog index template

---

translations/messages+intl-icu.bg.xlf
translations/messages+intl-icu.ca.xlf
translations/messages+intl-icu.cs.xlf
translations/messages+intl-icu.de.xlf
translations/messages+intl-icu.en.xlf
translations/messages+intl-icu.es.xlf
translations/messages+intl-icu.fr.xlf
translations/messages+intl-icu.hr.xlf
translations/messages+intl-icu.id.xlf
translations/messages+intl-icu.it.xlf
translations/messages+intl-icu.ja.xlf
translations/messages+intl-icu.nl.xlf
translations/messages+intl-icu.pl.xlf
translations/messages+intl-icu.pt_BR.xlf
translations/messages+intl-icu.ro.xlf
translations/messages+intl-icu.ru.xlf
translations/messages+intl-icu.sl.xlf
translations/messages+intl-icu.tr.xlf
translations/messages+intl-icu.uk.xlf
translations/messages+intl-icu.zh_CN.xlf

As pointed by @stof in #890, translations files does no longer take in account variables because of the `+intl-icu` suffix in translation files. This PR fix that!

Fix translations files with ICU message formater

---

templates/bundles/TwigBundle/Exception/error500.html.twig

I know this is not the right fix ... but I can't fix it in any other way.
The error: if you comment the DATABASE_URL config in the .env file, you see a 500 error. In production, that 500 error page sometimes has CSS styles and sometimes hasn't. Example:
* This page shows styles: http://symfony-demo.test/index.php/en/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit
* This page doesn't: http://symfony-demo.test/index.php/en/blog/
This is just a temporary fix because we need the Symfony Demo to work perfectly for some SymfonyCon session.

Temporary fix for the styles of the error 500 page

---

translations/validators+intl-icu.bg.xlf
translations/validators+intl-icu.ca.xlf
translations/validators+intl-icu.cs.xlf
translations/validators+intl-icu.de.xlf
translations/validators+intl-icu.en.xlf
translations/validators+intl-icu.es.xlf
translations/validators+intl-icu.fr.xlf
translations/validators+intl-icu.hr.xlf
translations/validators+intl-icu.id.xlf
translations/validators+intl-icu.it.xlf
translations/validators+intl-icu.ja.xlf
translations/validators+intl-icu.nl.xlf
translations/validators+intl-icu.pl.xlf
translations/validators+intl-icu.pt_BR.xlf
translations/validators+intl-icu.ro.xlf
translations/validators+intl-icu.ru.xlf
translations/validators+intl-icu.sl.xlf
translations/validators+intl-icu.tr.xlf
translations/validators+intl-icu.uk.xlf
translations/validators+intl-icu.zh_CN.xlf

I've run a simple Symfony demo and if you try to edit a post with 5 tags, you get an error due to [MessageFormatter](http://php.net/manual/fr/class.messageformatter.php) from icu used in [IntlFormatter](https://github.com/symfony/translation/blob/master/Formatter/IntlFormatter.php). It's due to ```{{ limit }}``` in message.
No documentation about that but we can see in a [test](https://github.com/symfony/translation/blob/master/Tests/Formatter/IntlFormatterTest.php#L88) that ```{ variable }``` can be processed. So we must use ```{ limit }``` and no ```{{ limit }}``` in message translate with icu.
I think to submit a PR to translation component for we can use ```{{ limit }}``` or ```{ limit }``` syntax.

Fix dynamic translation with ICU

---

composer.json
composer.lock
config/bundles.php
config/packages/html_sanitizer.yaml
src/Utils/Markdown.php
symfony.lock

I would like to propose the usage of html-sanitizer in remplacement of HTMLPurifier.
html-sanitizer is well integrated in modern Symfony applications (autowiring / autoconfiguration), it is better suited than HTMLPurifier to sanitize user inputs such as Markdown, it is faster and it creates HTML that's simpler and easier to understand. It is also IMO easier to extends and configure.

Migrate from HTMLPurifier to html-sanitizer

---

composer.json

Merging https://github.com/symfony/demo/commit/e26780b8d740f9074383a4983fa4d8e4904b0878#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R92 brought back minimum stability to beta.
Since Symfony 4.3 is stable, I think it's safe to remove it.

Remove beta minimum stability

---

.travis.yml

In order to prevent things fixed in #982 I think we can check for missing assets on TravisCI
Tests should pass after merging #982

Fail CI if the repo is in a dirty state after building assets

---

bin/phpunit
phpunit.xml.dist

See https://github.com/symfony/demo/issues/992
And I also updated to phpunit 7.5

use phpunit 7.5

---

bin/phpunit

It's a following of #1000.
The `phpunit` binary looks [like this](https://github.com/symfony/recipes/blob/master/symfony/phpunit-bridge/4.3/bin/phpunit) for Symfony 4.3, we don't need `SYMFONY_PHPUNIT_REMOVE` lines too.
I also think we don't need `SYMFONY_PHPUNIT_DIR` lines but I'm not really sure (it's working fine without those lines in one of our app).

chore(phpunit): remove lines for `SYMFONY_PHPUNIT_REMOVE`

---

.travis.yml

I would argue that adding those parameters ensures linting that is more similar to the framework runtime in production:
symfony will parse tags in config yaml files and twig runtime might differ between dev and prod environment.
for example we would catch a forgotten `{{ dump() }}` in a twig template that way

Be more specific in linting twig and yaml files

---

.travis.yml

Add 2 tests with failures allowed :
For this 2 adds only :
- change memory_limit of PHP,
- add 'composer install' a  for 4.4 and 5.0 only
- change stability to dev
- change 'composer install' to 'composer update'
- suppress last (composer.json change)

Add symfony 4.4 and 5.0 to .travis.yml

---

src/Pagination/Paginator.php
src/Repository/PostRepository.php
templates/blog/index.html.twig

The current code uses an array to provide the pagination information. We did that as part of the quick proof-of-concept replacement of Pagerfanta library.
This PR proposes to replace that array by a proper object. The new design was based on the one proposed by EasyAdmin to also replace Pagerfanta (https://github.com/EasyCorp/EasyAdminBundle/pull/2777).

Added a Paginator object based on Doctrine's paginator

---

translations/validators+intl-icu.lt.xlf

Translate validator messages to Lithuanian, as validator translations were missing.

Lithuanian translations for validator

---

templates/blog/index.html.twig
translations/messages+intl-icu.bg.xlf
translations/messages+intl-icu.cs.xlf
translations/messages+intl-icu.de.xlf
translations/messages+intl-icu.en.xlf
translations/messages+intl-icu.es.xlf
translations/messages+intl-icu.fr.xlf
translations/messages+intl-icu.id.xlf
translations/messages+intl-icu.it.xlf
translations/messages+intl-icu.ja.xlf
translations/messages+intl-icu.lt.xlf
translations/messages+intl-icu.nl.xlf
translations/messages+intl-icu.pl.xlf
translations/messages+intl-icu.pt_BR.xlf
translations/messages+intl-icu.ro.xlf
translations/messages+intl-icu.ru.xlf
translations/messages+intl-icu.uk.xlf

All but the `pt_BR` translations are based on the translations available on the KnpPaginatorBundle. That bundle doesn't have any string equivalent to "current", so this is why this translation is missing in all languages, except for `pt_BR` and `en`.

Make paginator strings translatable

---

src/Controller/Admin/BlogController.php
src/Entity/Post.php
src/Form/PostType.php
tests/Controller/Admin/BlogControllerTest.php

I'm trying to fix #1045. 
We should make the `slug` unique because it's what we use to look for blog posts in the database. However, I can't make this work. If I define `UniqueEntity` on `title`, it works ... but if I define it on `slug`, it doesn't work (I can create any number of posts with the same slug). Anybody sees the error? Thanks!

Make blog post titles unique

---

.travis.yml

This check prevents us from having an out of sync composer's lock-file (For example, when someone forgot to commit composer.lock file: https://github.com/symfony/demo/pull/1066).

Validate composer files while TravisCI build

---

composer.json
composer.lock
symfony.lock

PHP version 7.2+ is already required by Symfony 5

Remove "symfony/polyfill-php72" from the dependencies

---

composer.json
composer.lock
public/.htaccess
symfony.lock

What about to add `symfony/apache-pack` to this project? We have had a few related issues about missing it: #1069, #1005, #711 . Basically, it's a really small package that just adds `.htaccess` file into public/ dir and that's it. It would help Apache users and does not do any harm to others I think, so why not have it out of the box?

Require symfony/apache-pack package

---

phpunit.xml.dist
tests/Utils/ValidatorTest.php

PHPUnit 7 is not maintained anymore so we should update to version 8 :blush: 
See https://phpunit.de/supported-versions.html

use phpunit 8

---

composer.json
composer.lock
src/Twig/AppExtension.php

This PR replace `twig/twig` and `symfony/twig-bundle` with `symfony/twig-pack` which also install `twig/extra-bundle` that is require since #1080 and the addition of `Twig\Extra\TwigExtraBundle\TwigExtraBundle::class` in `bundles.php`
It also bump symfony packages to `v5.0.5`

Replace twig and twig-bundle with twig-pack

---

.travis.yml

I hope I did enough Googling. I really tried to find a reason to keep `sudo :false` in 2020 but it seems that it has no effect anymore.
I even tried to `sudo echo foo` during Travis' `install` phase and that works with and without `sudo: false`.
Docs: https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
Blog post stating "If you currently specify sudo: false in your .travis.yml, we recommend removing that configuration soon": https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
I also created a PR for the Symfony docs: https://github.com/symfony/symfony-docs/pull/13675

Remove unnecessary historic configuration: 'sudo: false'

---

config/packages/doctrine_migrations.yaml
config/services.yaml

Related to https://github.com/symfony/recipes/issues/718

Move doctrine migrations away from src

---

composer.json
composer.lock
symfony.lock

As suggested by composer 2 when trying to upgrade deps.

Fix compat with Composer 2 by using composer/package-versions-deprecated instead of ocramius/package-versions

---

config/packages/security.yaml

Hello,
I published a Symfony bundle [ecphp/cas-bundle](https://packagist.org/packages/ecphp/cas-bundle), that bundle has a [Symfony flex recipe](https://github.com/symfony/recipes-contrib/blob/master/ecphp/cas-bundle/2.0/manifest.json).
When users are trying the bundle against the Symfony demo (`symfony new project --demo`), it fails during installation because the flex recipe copies configuration files from the bundle into the app config directory.
Among the copied files, there is [this one in particular](https://github.com/ecphp/cas-bundle/blob/master/Resources/config/packages/dev/cas_security.yaml), which contains a new security user provider.
The demo app has a firewall already configured to use the only existing provider: [database_users](https://github.com/symfony/demo/blob/master/co …

Specify default security user provider.

---

src/Repository/PostRepository.php

These redundant `u()` cause type errors when using `declare(strict_types = 1)`.

Remove redundant u() from PostRepository::extractSearchTerms()

---

.php_cs.dist
.travis.yml
composer.json
composer.lock
config/packages/doctrine_migrations.yaml
symfony.lock

Dependencies were updated with Composer 2 RC1.

Updated backend dependencies

---

translations/validators+intl-icu.es.xlf

There is a missing string translation from the English version.

Add missing spanish translation

---

src/Entity/Post.php
src/Pagination/Paginator.php
src/Repository/PostRepository.php
tests/Controller/BlogControllerTest.php

This continues #1160 to refactor some code.

Move some constant to a better place

---

config/services.yaml
src/Command/ListUsersCommand.php
src/Entity/Post.php
src/EventSubscriber/CommentNotificationSubscriber.php
src/Form/Type/DateTimePickerType.php
src/Form/Type/TagsInputType.php
src/Security/PostVoter.php
src/Twig/SourceCodeExtension.php

This PR adds some type declarations where they were missing before.

Add missing type declarations

---

composer.json
config/packages/framework.yaml
config/packages/prod/deprecations.yaml
config/packages/prod/monolog.yaml
config/packages/security.yaml
config/preload.php
config/services.yaml
src/Kernel.php
symfony.lock

This PR is to update recipes to its latest versions 
- symfony/framework-bundle 
- symfony/security-bundle
- symfony/monolog-bundle
- doctrine/doctrine-fixtures-bundle
- doctrine/doctrine-migrations-bundle

Updates symfony recipes to latest

---

package.json
yarn.lock

I have updated js dependencies for two reasons:
1. Webpack Encore requires version ^9.0.1 of sass-loader, but your version (7.3.1) is too old. T
he related feature will probably not work correctly.
2. Vulnerability in "object-path" <= 0.11.4

Updated JavaScript dependencies

---

.github/workflows/ci.yaml
.gitignore
composer.json
composer.lock
symfony.lock

We can remove this because we're now using PHP-CS-Fixer via a Docker image created by @OskarStark and run via GitHub Actions (see https://github.com/symfony/demo/pull/1171)

Removed friendsofphp/php-cs-fixer from dev dependencies

---

.github/workflows/ci.yaml
composer.json
composer.lock
src/Controller/BlogController.php
tests/Command/AddUserCommandTest.php

This project is not compatible with PHP 8 at the moment because of `doctrine/dbal`.
The problem is that to upgrade DBAL we need to upgrade our PHP requirement too. We require PHP `^7.2.9` (to match Symfony's own requirements) but the DBAL version compatible with PHP 8 requires `^7.3|^8.0`.
So, I guess we can make an exception and require PHP 7.3 in this project to fix this issue. @nicolas-grekas do you agree with this solution or do you think we can solve this differently? Thanks!

Allow using PHP 8 to run the project

---

config/packages/framework.yaml

We don't need this since the changes introduced in #427 and this goes in sync with the official Symfony recipe: https://github.com/symfony/recipes/pull/892

Disable HTTP method override

---

.github/workflows/ci.yaml

We should not need to treat PHP 8.0 differently anymore in CI.

Remove PHP 8 workarounds from CI

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml

To prevent dependabot from triggering the lint workflow twice

Update workflow triggers

---

.github/workflows/tests.yaml

There's no need to test all PHP version in all OS ... and that'll reduce the GitHub Actions minutes consumed for the entire Symfony organization.

Reduce the number of tests made by GitHub Actions

---

composer.lock

Upgrade deps to fix known vulnerability:
```
Symfony Security Check Report
=============================
1 package has known vulnerabilities.
symfony/security-http (v5.3.1)
------------------------------
* [CVE-2021-32693][]: Authentication granted to all firewalls instead of just one
[CVE-2021-32693]: https://symfony.com/cve-2021-32693
Note that this checker can only detect vulnerabilities that are referenced in the security advisories database.
Execute this command regularly to check the newly discovered vulnerabilities.
```

Update deps to fix security-http vulnerability

---

tests/Command/AddUserCommandTest.php

In every test job we have skipped tests:
```
Run vendor/bin/simple-phpunit -v
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.5
Configuration: /home/runner/work/demo/demo/phpunit.xml.dist
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
Testing 
SSSS...........................................                   47 / 47 (100%)
Time: 00:14.918, Memory: 74.50 MB
There were 4 skipped tests:
1) App\Tests\Command\AddUserCommandTest::testCreateUserNonInteractive with data set #0 (false)
`stty` is required to test this command.
/home/runner/work/demo/demo/tests/Command/AddUserCommandTest.php:35
2) App\Tests\Command\AddUserCommandTest::testCreateUserNonInteractive …
```

Install stty required for tests on ubuntu-latest

---

tests/Command/AbstractCommandTest.php
tests/Command/AddUserCommandTest.php
tests/Command/ListUsersCommandTest.php

The command list user was not tested until now, and that's quite sad because it's one of the only parts of the code that actually sends an email. Symfony has some tools for testing emails, let's use them!
I also refactored a little bit of command testing since there was an identical piece of code between test cases. (instantiating the command)

Add a test for command ListUsers (test emails)

---

tests/Command/AbstractCommandTest.php
tests/Command/AddUserCommandTest.php

Fixes an issue in this discussion: https://github.com/symfony/demo/pull/1133/files#r665459095

Do not skip user list command test because of stty

---

phpstan-baseline.neon

The PHPUnit baseline apparently has been created with an older version of PHPStan. I have recreated it with the latest version 1.2.0 which is also currently used by the CI.

Update PHPStan baseline

---

config/packages/assets.yaml

https://symfony.com/blog/new-in-symfony-5-4-misc-features-part-1#strict-mode-for-missing-assets

Enable strict mode on assets

---

config/packages/assets.yaml

Fix breaking changes introduced by #1278
Asset urls generated in `entrypoints.json` https://github.com/symfony/demo/blob/a7a975e2938b0568b493406ce914ac0866b6dd58/public/build/entrypoints.json#L13  are not meant to be mapped with `manifest.json`
https://github.com/symfony/demo/blob/a7a975e2938b0568b493406ce914ac0866b6dd58/public/build/manifest.json#L2
The only place where the twig `asset` function is used, is for a file that is not in the manifest: https://github.com/symfony/demo/blob/a7a975e2938b0568b493406ce914ac0866b6dd58/templates/base.html.twig#L17

Assets manifest is not necessary with Webpack Encore

---

templates/base.html.twig

Ref https://symfony.com/doc/current/frontend/encore/simple-example.html#configuring-encore-webpack

Move JavaScript entry function in the HTML head

---

src/Twig/AppExtension.php
src/Twig/SourceCodeExtension.php

While reading the doc and opening https://github.com/symfony/symfony-docs/pull/16292 as well

Add some doc for Twig Extension

---

src/Command/AddUserCommand.php
src/Command/DeleteUserCommand.php
src/Command/ListUsersCommand.php

I wanted to test PHP 8 install on my new machine, thus tried some features on this project as it now requires v8
I followed https://symfony.com/blog/new-in-symfony-5-3-lazy-command-description
Feel free to close, but I think it could be useful to showcase new way on this Symfony demo project as it is kind off an entry point, also Controllers uses this feature

Leverage PHP 8 attributes to configure Command

---

src/Form/CommentType.php

Fixes:
An exception has been thrown during the rendering of a template ("An error has occurred resolving the options of the form "Symfony\Component\Form\Extension\Core\Type\TextareaType": The option "formaction" does not exist.

Fix an exception in CommentType

---

config/packages/translation.yaml
src/EventSubscriber/CommentNotificationSubscriber.php
templates/admin/blog/edit.html.twig
templates/bundles/TwigBundle/Exception/error.html.twig
templates/bundles/TwigBundle/Exception/error403.html.twig
templates/bundles/TwigBundle/Exception/error404.html.twig
templates/bundles/TwigBundle/Exception/error500.html.twig

Even if it works with`%var%` I think without is better, wdyt?
Ref https://symfony.com/doc/current/translation/message_format.html
Also added a direct link to doc

Fix translator parameters

---

composer.json
src/Controller/Admin/BlogController.php
src/Controller/BlogController.php
src/Security/PostVoter.php
src/Utils/Validator.php

Add some comments while reading some source code
Ref https://symfony.com/doc/current/setup.html#the-symfony-demo-application

Add various comments in the codebase

---

composer.json
composer.lock

This package was added in the past to force keeping support for composer 1 when using doctrine/orm. In the meantime, doctrine/orm has switched to using that package directly, making this root requirement useless. And in the next releases of doctrine/orm and doctrine/dbal, they are migrating to use composer-runtime-api (dropping support for composer 1) instead of using this plugin, as part of the effort to fade out that compat plugin.
Refs https://github.com/symfony/symfony/issues/44726
The package is still present for now (and so still needed in the list of allowed plugins too) because doctrine packages require it. But this will change in their next releases for DBAL, ORM and Migrations (the PRs are already merged)

Remove the dependency on composer/package-versions-deprecated

---

config/packages/security.yaml
templates/base.html.twig

The login form already had CSRF protection, but logout didn't yet in this demo application. Generally, I think it's a good idea to add CSRF protection to logout. At the very least, it avoids annoying situations where a website can force users to logout from your service on each visit. But depending on the type of application, things can also get more serious and cause actual security issues when CSRF on logout isn't enabled.
Fortunately, CSRF protection on logout is quite easy using the `logout_path()` helper: it automatically knows the logout URL of the current firewall and it automatically adds the correct CSRF token to the URL. I think the logout path/url helpers are little known gems in Symfony, so let's showcase them :)

Use logout_path() helper + add CSRF protection to logout

---

config/packages/prod/monolog.yaml

Using stderr in prod by default is a good idea (we made the change in the official recipe a while ago -- https://github.com/symfony/recipes/blob/master/symfony/monolog-bundle/3.7/config/packages/monolog.yaml#L51) as it makes it work out of the box with anything compatible with Docker, including Platform.sh.

Use stderr for logging in prod

---

src/Controller/Admin/BlogController.php

The doc now suggests to use PHP attributes instead of "old" annotation for "IsGranted" instruction.
Sorry if my PR format doesn't match with your requirements. I just wanna help. :)

Update PHP doc about annotations IsGranted

---

src/Controller/BlogController.php

Hi,
Considering symfony/demo require php 8.0.2 I guess it'safe to use nullsafe instead ternary to get tag's name if `Tag` exist

use nullsafe operator in BlogController

---

.github/workflows/lint.yaml

Changed directory name from .symfony to .symfony5
See details here https://github.com/symfony-cli/symfony-cli/commit/5301ebfa8f5918cae7fa0bf63c86f84dbd70f599

Update lint.yaml to fix security check

---

templates/blog/search.html.twig

Remove dead HTML code

---

.github/workflows/lint.yaml

Since Composer 2.4, there is a new command called audit, that outputs a list of reported security vulnerabilities for the list of packages versions currently installed.
This removes the need to download and install Symfony CLI

Use 'composer audit' instead of 'symfony check:security'

---

.github/workflows/lint.yaml
.github/workflows/tests.yaml

Deprecation warnings:
- Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/cache, actions/checkout, shivammathur/setup-php
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix GitHub Actions deprecation warnings

---

config/packages/security.yaml
templates/security/login.html.twig

"Remember me" is a common functionality in login forms and I noticed that the demo application does not have it.
This PR is a small change and any user can easily find that in the documentation, but I believe that this is still a relevant addition in order to make this demo a bit more "complete" and show that Symfony can provide common functionalities out of the box.
I also didn't find any discussion (issue/pr) about this functionality so I don't know whether it was intended to not have it in the demo app.
What do you think?

Added "remember me" feature in the login form

---

src/Controller/UserController.php
src/Form/ChangePasswordType.php

https://symfony.com/blog/new-in-symfony-6-2-security-improvements-part-2#improved-password-form-field
Fixes #1378

[Sf62] Use the new 'hash_property_path' option of the PasswordType field

---

.github/workflows/tests.yaml

I think this step can be remove since "symfony/flex" is already part of the project dependencies.
https://github.com/symfony/demo/blob/v2.2.0/composer.json#L28

CI: Remove "Require symfony/flex" step from tests

---

composer.json

The plugin composer/package-versions-deprecated is no longer in use.
Followup of #1310

Remove composer/package-versions-deprecated from allow-plugins

---

src/Controller/BlogController.php

The $param is typed int. So if the routing param does not fit into an int, PHP will throw a TypeError. This in turn would trigger an 500 internal server error. So by requesting a too big page, e.g. `/de/blog/page/147483647147483647147483647`, one can trigger internal errors which should not be possible.
I don't think there is an easy solution to this general problem that Symfony could automatically provide. So the best solution seems to be to limit the size of the routing placeholder. With this limit the page will always fit into an int even on a 32-bit platform.

Limit page size to prevent integer overflow

---

composer.json
composer.lock
config/services.yaml
phpstan-baseline.neon
phpstan.neon.dist
src/Controller/BlogController.php
tests/Command/AddUserCommandTest.php
tests/object-manager.php

Add Symfony and Doctrine PHPStan extensions

---

README.md

After merging #1399, I thought about tweaking `README` contents to make it more clear the different alternative ways of installing and using this project.

Update the README contents

---

src/Controller/Admin/BlogController.php
src/Controller/BlogController.php
src/Controller/UserController.php

php8: fixed named arguments order

---

composer.lock
src/Command/AddUserCommand.php
src/Command/DeleteUserCommand.php
src/Command/ListUsersCommand.php
src/DataFixtures/AppFixtures.php
src/EventSubscriber/CheckRequirementsSubscriber.php
src/EventSubscriber/CommentNotificationSubscriber.php
src/EventSubscriber/ControllerSubscriber.php
src/EventSubscriber/RedirectToPreferredLocaleSubscriber.php
src/Form/DataTransformer/TagArrayToStringTransformer.php
src/Form/PostType.php
src/Form/Type/DateTimePickerType.php
src/Form/Type/TagsInputType.php
src/Pagination/Paginator.php
src/Twig/AppExtension.php

+ other PHP 8.1 upgrades (rector)

chore: readonly properties

---

composer.lock
config/packages/security.yaml
src/Command/AddUserCommand.php
src/Controller/Admin/BlogController.php
src/Controller/UserController.php
src/DataFixtures/AppFixtures.php
src/Entity/User.php

Before we had to hard-code roles strings: 
```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
class PostController extends Controller
{
/**
* @IsGranted("ROLE_ADMIN")
*
* or use @Security for more flexibility:
*
* @Security("is_granted('ROLE_ADMIN') and is_granted('ROLE_FRIENDLY_USER')")
*/
public function index()
{
// ...
}
}
```
But with attributes, can use constants. I find this cleaner. I have already used this on several projects and I didn't find drawbacks.

cleanup: use roles constants

---

templates/default/_flash_messages.html.twig

Add class "show" to avoid invisible alerts 
See https://github.com/symfony/demo/issues/1440

Show invisible alerts (fix #1440)

---

assets/js/doclinks.js
src/Controller/BlogController.php

* update doclinks.js (and remove jquery usage)
* update some links in BlogController
* remove references to SensioFrameworkExtraBundle

Update documentation links

---

src/Controller/Admin/BlogController.php

The isSubmitted() _must_ be called before
[src/Symfony/Component/Form/Form.php](https://github.com/symfony/symfony/blob/6637b78a4fcba7cef818f2a022e096d503690ac5/src/Symfony/Component/Form/Form.php#L646-L657)
```php
public function isValid(): bool
{
if (!$this->submitted) {
throw new LogicException('Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() and ensure that it\'s true before calling Form::isValid().');
}
if ($this->isDisabled()) {
return true;
}
return 0 === \count($this->getErrors(true));
}
```

Fix comment stating isSubmitted is optional

---

src/Controller/BlogController.php

While reading this, I found that pointing messenger here can be valuable (logic of decoupling)
Also, reading the code itself of the dispatch, I remind my old PR https://github.com/symfony/symfony-docs/pull/17035
there is no doc referencing the new `->dispatch(new ClassName())` as far as I see in https://symfony.com/doc/current/components/event_dispatcher.html#dispatch-the-event

Add notice to messenger for async code

---

src/Controller/Admin/BlogController.php
src/Controller/BlogController.php
src/Controller/UserController.php
tests/Controller/Admin/BlogControllerTest.php
tests/Controller/UserControllerTest.php

This PR provides 303 redirections, see issue #1433

303 redirections

---

config/packages/doctrine.yaml

I didn't know about this feature. It's very useful to find the origin of a specific query from the doctrine profiler panel.
I think it's a good idea to activate it on symfony/demo, as it allows you to demonstrate this functionality.

Enable backtraces in Doctrine profiler

---

src/Twig/SourceCodeExtension.php
templates/debug/source_code.html.twig

Create `link_source_file` helper to replace internal WebProfiler helper

---

src/Form/PostType.php
src/Repository/PostRepository.php
src/Twig/SourceCodeExtension.php

Found with PHPStorm "inspect code" feature.

Misc minor fixes

---

config/packages/security.yaml
src/Controller/SecurityController.php
tests/Controller/UserControllerTest.php

I checked the list of Symfony 6.4 features, and this is the only one that I think it fits this application. So, let's use it.

Simplify logout

---

config/services.yaml
src/Command/ListUsersCommand.php
src/Controller/UserController.php
src/EventSubscriber/CommentNotificationSubscriber.php

I'm not sure this is something you want to do: replacing Yaml config for attribute for class alias, to use the `#[Autowire]` attribute available [since Symfony 6.1](https://symfony.com/blog/new-in-symfony-6-1-service-autowiring-attributes).
I did the change, so let you decide if that's good or not for the demo.

Use `#[Autowire]` attribute instead of Yaml config

---

.github/workflows/lint.yaml
.github/workflows/tests.yaml

Composer installs the dependencies from a composer.lock file 
The result doesn't depend on the PHP version that is used in CI

CI: Share composer cache across php versions

---

config/services.yaml
src/Controller/UserController.php
tests/Controller/UserControllerTest.php

Proposition from @chalasr: https://github.com/symfony/symfony/pull/52833#issuecomment-1839135127
The logout URL generator should be used to create links with CSRF protection. In this case, the action is already secured by the form, the redirection is not necessary.

Use `Security::logout()` instead of redirecting to the logout url

---

composer.json

After merging #1449 I saw this error when running the app:

Add a missing command to build Sass files

---

src/EventSubscriber/CommentNotificationSubscriber.php

The config files have been merged and `when@dev` is now used.

Fix comment about mailer config

---

templates/base.html.twig

On symfony.com we recently added some subtle [CSS view transitions](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API).
I propose to add this little change that adds a very subtle cross-fade animation between page loads. For now, it only works on Google Chrome browsers.

Add a subtle cross-fade view transition

---

src/Command/AddUserCommand.php
src/Controller/BlogController.php
src/DataFixtures/AppFixtures.php
src/Entity/Post.php
src/EventSubscriber/CommentNotificationSubscriber.php
src/EventSubscriber/RedirectToPreferredLocaleSubscriber.php
src/Form/DataTransformer/TagArrayToStringTransformer.php
src/Repository/PostRepository.php
src/Twig/AppExtension.php
src/Twig/SourceCodeExtension.php

Multiple-line code blocks is being separated with new line from single-line code blocks.
Also php-cs-fixer suggested fix: functions with default null arguments should accept null value.

More consistent code style

---

.github/workflows/lint.yaml
.github/workflows/tests.yaml

Fixes warnings:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

[CI] Bump github actions

---

config/packages/framework.yaml
config/packages/security.yaml
config/routes.yaml
config/services.yaml
src/EventSubscriber/RedirectToPreferredLocaleSubscriber.php
src/Twig/AppExtension.php

I never liked the `app_locales` parameter: https://github.com/symfony/demo/blob/main/config/services.yaml#L9
But we need it for the route locale requirements.
I was digging into how to improve this ... and realized that if we use the standard [enabled_locales](https://symfony.com/doc/current/reference/configuration/framework.html#enabled-locales) config option from Symfony, the `{_locale}` parameter included in the URLs is automatically restricted to those values.
So, we can simplify code by moving to `enabled_locales` without losing any functionality.

Refactor how we define the available locales

---

src/DataFixtures/AppFixtures.php
src/Entity/Comment.php
src/Entity/Post.php
src/Form/Type/DateTimePickerType.php
src/Repository/PostRepository.php

Since we use SQLite, it looks like we don't need a DB migration to make this change work. But maybe I'm wrong. Thanks for reviewing this.

Only use immutable datetime objects

---

src/Entity/User.php

This is not needed since a long time ago.

Remove the salt from the user entity

---

src/EventSubscriber/RedirectToPreferredLocaleSubscriber.php

Hello, I opened this tiny PR because I noticed this little error in a comment.
Despite the size, I think it's a rather confusing error, because not knowing how locales work myself, I am not sure whether it was `an` or `no` that I should remove to fix the comment. 
Hopefully I got it right 🙏🏽

Fix small comment hiccup

---

.github/workflows/lint.yaml
translations/messages+intl-icu.bn.xlf
translations/messages+intl-icu.ne.xlf

These issues were found with the cool new `lint:translations` command added to Symfony 7.2 (see https://symfony.com/blog/new-in-symfony-7-2-translations-linter)

Fix some translation issues

---

.env.dev
.env.test

For the flex recipe that generates the APP_SECRET to work the `.env.dev` file needs to exist.
Fixes #1536

Add an empty .env.dev file

---

assets/styles/app.scss

Bootstrap dropped the jumbotron component 
https://getbootstrap.com/docs/5.3/migration/#jumbotron

Add a background color to the jumbotron on the homepage

---

.devcontainer/devcontainer.json

If it is executed as part of the updateContentCommand step, the container creation fails.
importmap:install is executed by composer install though (part of the auto-scripts), which executes just fine in Codespaces.
Part of #1542

Remove importmap:install command from devcontainer.json

---

src/DataFixtures/AppFixtures.php

The class parameter is now mandatory for references.
Fixes exception when running `bin/console doctrine:fixtures:load`:
```
[ArgumentCountError]
Too few arguments to function Doctrine\Common\DataFixtures\AbstractFixture::getReference(), 1 passed in /workspace/project/src/DataFi
xtures/AppFixtures.php on line 143 and exactly 2 expected
```
Related to: https://github.com/doctrine/data-fixtures/pull/464

Update the data fixtures

---

config/packages/translation.yaml
config/routes.yaml
config/services.yaml

I changed the `locale` setting to put the `app.` prefix in order to follow best practices.
https://symfony.com/doc/current/best_practices.html#use-short-and-prefixed-parameter-names :
> Consider using app. as the prefix of your [parameters](https://symfony.com/doc/current/configuration.html#configuration-parameters) to avoid collisions with Symfony and third-party bundles/libraries parameters. Then, use just one or two words to describe the purpose of the parameter

Use `app.` prefix for `parameters`

---

.devcontainer/devcontainer.json

Part of https://github.com/symfony/demo/issues/1542
GitHub Codespaces runs the application behind a proxy. In order to get correctly generated URLs, proxy headers must be allowed.
Also update to PHP 8.4

Set trusted proxies for running in Codespace

---

.github/workflows/lint.yaml
.github/workflows/tests.yaml

I think there is little benefit anymore for this repository to have a composer cache in the CI workflows. With composer v2 the dependencies are downloaded in parallel which is a lot faster than composer v1. This makes the performance gains from the cache small since it also takes time to setup and save or restore the cache.
Also the chance for a cache hit is low:
- This repository has low traffic and the cache expires after a week which reduces the chance for a cache hit. 
- Every branch / PR get it's own cache which again reduces the chance for a cache hit.
So I purpose to remove the composer cache to simplify the workflows.
Replaces: #1538

Remove the composer cache from the CI workflows

---

composer.json

I don't know if the demo is intended to work in production mode. However since the assets are no longer bundled, but generated during `composer install` with `sass:build` i think it makes sense to ensure that bootstrap is always available by moving it to the required dependencies.
Fixes #1509

Move the twbs/bootstrap dependency from require-dev to require

---

.github/workflows/lint.yaml
composer.lock

in #1540 it was forgotten to sync the `composer.lock` file

run composer validate before installing dependencies

---

.gitignore

Remove duplicates and leftovers from symfony/phpunit-bridge and previous bundled assets from the `.gitignore` file

Remove duplicates and leftovers from .gitignore

---

.github/workflows/lint.yaml

By running PHP CS Fixer on the lowest supported PHP version of this project, which is currently PHP 8.2, PHP CS Fixer can also catch the use of invalid syntax that works only on newer PHP versions.
This [doc](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/support_new_PHP_version.rst) also recommends to run PHP CS Fixer on same PHP version as platform PHP version of the codebase.

CI: run PHP CS Fixer on PHP 8.2

---

.github/workflows/end_to_end_tests.yaml

To avoid issues in the future, I propose to add a daily test that checks that this application is installable and works using different methods: Symfony CLI, Composer and Git clone.

Add End to End tests on GitHub CI

---

.github/workflows/end_to_end_tests.yaml

I did some fixes and tweaks for the demo install test.
I did multiple commit to make it easier to review

[CI] Fixes and tweaks for the demo install test

---

assets/styles/app.scss
templates/security/login.html.twig

This updates the login page to make use of the bootstrap v5 classes

[Bootstrap v5] Update login page

---

assets/styles/app.scss
templates/admin/blog/show.html.twig
templates/blog/index.html.twig
templates/default/homepage.html.twig

Bootstrap v5 dropped the jumbotron component as it can be replicated with utility classes
https://getbootstrap.com/docs/5.3/examples/jumbotrons/

[Bootstrap v5] Replace jumbotron with utility classes

---

assets/js/flatpicker.js
src/Form/Type/DateTimePickerType.php
templates/form/fields.html.twig

Also fixes the alignment of the input fields and the add-ons

[flatpickr] Fix flatpickr calendar buttons and localization
